#!/bin/sh
#
# Run all tests
#
tests/test0
tests/backup-bacula-test
tests/sparse-test
tests/compressed-test
tests/sparse-compressed-test
tests/wierd-files-test
tests/two-jobs-test
tests/dev-test-root
tests/etc-test-root
tests/lib-test-root
cat test.out
