#!/bin/sh
#
# Run all tests
#
tests/test0
tests/backup-bacula-test
tests/sparse-test
tests/compressed-test
tests/sparse-compressed-test
tests/wierd-files-test
tests/two-jobs-test
echo " "
echo " "
echo "Test results"
echo " "
cat test.out
