#!/bin/sh
#
# Run all tests
#
echo " "
echo " " >>test.out
echo "Start non-root disk tests"
echo "Start non-root disk tests" >>test.out
ctest -R all-non-root:
echo "End non-root disk tests"
echo "End non-root disk tests" >>test.out
