#!/bin/sh
#
# Run all tape tests
#
. ./config.out
if test ! x$AUTOCHANGER = x/dev/null ; then
   mtx -f $AUTOCHANGER load 1 >/dev/null &2>/dev/null
fi
echo " "
echo " " >>test.out
echo "Start all non-root tape tests"
echo "Start all non-root tape tests" >>test.out
nice tests/ansi-label-tape
nice tests/backup-bacula-tape
nice tests/btape-fill-tape
nice tests/fixed-block-size-tape
nice tests/four-concurrent-jobs-tape
nice tests/four-jobs-tape
nice tests/incremental-tape
nice tests/relabel-tape
nice tests/restore-by-file-tape
nice tests/small-file-size-tape
nice tests/truncate-bug-tape
nice tests/two-pool-tape
nice tests/2drive-incremental-2tape
nice tests/bscan-tape
nice tests/verify-vol-tape
echo "End all non-root tape tests"
echo "End all non-root tape tests" >>test.out
