#!/bin/sh
#
# Run all tape tests
#
cp test.out test1.out
tests/test0
tests/backup-bacula-tape
tests/bscan-tape
tests/btape-fill-tape
tests/fixed-block-size-tape
tests/four-concurrent-jobs-tape
tests/four-jobs-tape
tests/incremental-tape
tests/relabel-tape
tests/restore-by-file-tape
tests/small-file-size-tape
tests/truncate-bug-tape
tests/two-pool-tape
echo " "
echo " "
echo "Test results"
cat test.out
scripts/cleanup
