#!/bin/sh
#
# Run all tape tests
#
. ./config.out
if test ! x$AUTOCHANGER = x/dev/null ; then
   mtx -f $AUTOCHANGER load 1 >/dev/null &2>/dev/null
fi
echo " "
echo " " >>test.out
echo "Start all non-root tape tests"
echo "Start all non-root tape tests" >>test.out
nice ctest -R all-non-root-tape:
echo "End all non-root tape tests"
echo "End all non-root tape tests" >>test.out
