#!/bin/sh
#
# Run all root tests
#
echo " "
echo " " >>test.out
echo "Start root tests"
echo "Start root tests" >>test.out
nice ctest -R all-root:
echo "End root tests"
echo "End root tests" >>test.out
