#!/bin/sh
#
# Run all tape tests
#
echo "Start two tape tests"
echo "Start two tape tests" >>test.out
nice tests/two-volume-tape
nice tests/incremental-2tape
echo "End two tape tests"
echo "End two tape tests" >>test.out
