#!/bin/sh
/home/kern/bacula/bin/startmysql
nice make setup
./starttime
if [ ! -e bin/tape_options ] ; then
  touch bin/tape_options
fi
nice ./all-tape-and-file-tests
./endtime
nice ./all-non-root-2tape-tests
./endtime
