#!/bin/sh
/home/kern/bacula/bin/startmysql
make setup
./starttime
if [ ! -e bin/tape_options ] ; then
  touch bin/tape_options
fi
./all-tape-and-file-tests
if [ ! -e bin/tape_options ] ; then
  touch bin/tape_options
fi
./all-non-root-2tape-tests
./endtime
