#!/bin/sh
#
# test only the disk based regression scripts
#
# Include full output
save_debug=${REGRESS_DEBUG}
REGRESS_DEBUG=1
export REGRESS_DEBUG
svn update
scripts/config_dart
nice ctest -D Experimental -R "^tape:"
if [ $? != 0 ] ; then
   echo "ctest failed re-running Submit"
   ctest -D ExperimentalSubmit
fi
REGRESS_DEBUG=${save_debug}
