#!/bin/sh
#
# run both the disk and the tape based regression tests.
#
# Include full output
echo "Begin nightly-all `date`"
save_debug=${REGRESS_DEBUG}
REGRESS_DEBUG=1
export REGRESS_DEBUG
svn update
scripts/config_dart
nice ctest -D Nightly -R "^(disk|tape|changer):"
if [ $? != 0 ] ; then
   echo "ctest failed re-running Submit"
   ctest -D NightlySubmit
   if [ $? != 0 ] ; then
      echo "Submit failed, waiting 5 mins"
      sleep 300
      echo "ctest failed re-running Submit a second time"
      ctest -D NightlySubmit
   fi
fi
REGRESS_DEBUG=${save_debug}
echo "End nightly-all `date`"
