#!/bin/sh
#
# run both the disk and the tape based regression tests.
#
# Include full output
save_debug=${REGRESS_DEBUG}
REGRESS_DEBUG=1
export REGRESS_DEBUG
svn update
scripts/config_dart
nice ctest -D Nightly -R "all-non-root.*"
if [ $? != 0 ] ; then
   echo "ctest failed re-running Submit"
   ctest -D NightlySubmit
fi
REGRESS_DEBUG=${save_debug}
