#!/bin/sh
#
# test only the disk based regression scripts
#
# Include full output
LANG=C
echo "Begin nightly-disk `date`"
save_debug=${REGRESS_DEBUG}
REGRESS_DEBUG=1
export REGRESS_DEBUG
rm -rf Testing
rm -f dumps/*
git checkout master
git pull
#
# Temp switch to branch Branch-5.0 NB this leaves you on a headless
#    branch, but it works for building and testing.
#
#git checkout `git branch -r | grep "5\.0" | head -1`
#if [ $? -ne 0 ]; then
#   git checkout master
#fi
make distclean
scripts/config_dart
make setup
nice ctest -D Nightly -R "^disk:"
rtn=$?
i=0
while [ $i -le 5 ]; do
   if [ $rtn = 0 ] || [ "$rtn" = "8" ]; then
      break;
   fi
   echo "Submit failed, waiting 5 mins"
   sleep 300
   echo "ctest failed re-running Submit"
   ctest -D NightlySubmit
   rtn=$?
   i=`expr $i + 1`
done
REGRESS_DEBUG=${save_debug}
echo "End nightly-disk `date`"
