#!/bin/sh
#
# Script to run a regression test with a time limit (in seconds)
#  this allows the script to be killed if say the SD crashes
#  due to an ASSERT.  Otherwise the script will hang for
#  a very long time, perhaps forever.
# Of course, this implies that all tests must terminate normally
#  within the timeout period (900 seconds).
#
if [ -f bin/timelimit ] ; then
   WARNTIME=900 KILLTIME=5 bin/timelimit $*
else
   nice $*
fi
