#!/bin/sh
#
#
TestName="action-on-purge-test"
JobName=AOP
. scripts/functions

cwd=`pwd`
scripts/cleanup
scripts/copy-test-confs

echo $src > $tmp/file-list
sed 's/Pool Type = Backup/Pool Type = Backup; ActionOnPurge = Truncate/' $conf/bacula-dir.conf > $tmp/1
cp $tmp/1 $conf/bacula-dir.conf

change_jobname CompressedTest $JobName
start_test

cat >tmp/bconcmds <<END_OF_DATA
@$out /dev/null
messages
@$out $tmp/log1.out
label storage=File volume=TestVolume001
label storage=File volume=TestVolume002
run level=full job=$JobName yes
wait
messages
@$out $tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select all storage=File done
yes
wait
messages
@#########################################################
@# Run a second job on TestVolume002
@#########################################################
@$out $tmp/log3.out
update volume=TestVolume001 volstatus=Used
messages
show pool
@$out $tmp/log1.out
run level=full job=$JobName yes
wait
messages
@#########################################################
@# Run a third job that will wait, and purge volume
@#########################################################
@$out $tmp/log3.out
update volume=TestVolume002 volstatus=Used
messages
@$out $tmp/log1.out
run level=full job=$JobName yes
@#wait mount
@sleep 5
messages
list volume
@# should continue on TestVolume001
sql
select VolumeName, ActionOnPurge FROM Media;

setdebug level=400 director
purge volume=TestVolume001
list volume
sql
select VolumeName, ActionOnPurge FROM Media;

mount storage=File
wait
@#########################################################
@# Test ActionOnPurge=Truncate Volume size should be small
@#########################################################
purge volume=TestVolume001
list volume
@#########################################################
@# Test ActionOnPurge=Truncate, then update it to None
@# Volume size should be normal
@#########################################################
update volume=TestVolume002 actiononpurge=none
purge volume=TestVolume002
@#########################################################
@# Display catalog settings for Pool and Media
@#########################################################
@$out $tmp/log4.out
sql
select VolumeName, ActionOnPurge FROM Media;
select Name, ActionOnPurge FROM Pool;

quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=File 
stop_bacula

check_two_logs
check_restore_diff

perl -e "die 'Volume size too big' if (-s '$tmp/TestVolume001' > 4096)"
if [ $? != 0 ]; then
    print_debug `ls -l $tmp/TestVolume001`
    bstat=2
fi

perl -e "die 'Volume size too small' if (-s '$tmp/TestVolume002' < 4096)"
if [ $? != 0 ]; then
    print_debug `ls -l $tmp/TestVolume002`
    bstat=2
fi

print_debug "Test if Pool record is ok"
r=`awk '/Default/ { print $4 }' $tmp/log4.out`
if [ "$r" != 1 ]; then
    print_debug "ActionOnPurge on Pool record should be 1"
    bstat=2
fi

print_debug "Test TestVolume001 if Media record is ok"
r=`awk '/TestVolume001/ { print $4 }' $tmp/log4.out`
if [ "$r" != 1 ]; then
    print_debug "ActionOnPurge on Media record should be 1"
    bstat=2
fi

print_debug "Test TestVolume002 if Media record is ok"
r=`awk '/TestVolume002/ { print $4 }' $tmp/log4.out`
if [ "$r" != 0 ]; then
    print_debug "ActionOnPurge on Media record should be 0"
    bstat=2
fi

end_test
