#!/bin/sh
#
#
TestName="action-on-purge-test"
JobName=AOP
. scripts/functions

cwd=`pwd`
scripts/cleanup
scripts/copy-test-confs

echo $src > $tmp/file-list
sed 's/Pool Type = Backup/Pool Type = Backup; ActionOnPurge = Truncate/' $conf/bacula-dir.conf > $tmp/1
cp $tmp/1 $conf/bacula-dir.conf

change_jobname CompressedTest $JobName
start_test

cat >tmp/bconcmds <<END_OF_DATA
@$out /dev/null
messages
@$out $tmp/log1.out
label storage=File volume=TestVolume001
run job=$JobName yes
wait
messages
@$out $tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select all storage=File done
yes
wait
messages
@# Test ActionOnPurge=Truncate Volume size should be small
@$out $tmp/log3.out
purge volume=TestVolume001
messages
show pool
@$out $tmp/log4.out
sql
select VolumeName, ActionOnPurge FROM Media;
select Name, ActionOnPurge FROM Pool;

quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=File 
stop_bacula

check_two_logs
check_restore_diff

perl -e "die 'Volume size too big' if (-s '$tmp/TestVolume001' > 4096)"
if [ $? != 0 ]; then
    print_debug `ls -l $tmp/TestVolume001`
    bstat=2
fi

print_debug "Test if Pool record is ok"
r=`awk '/Default/ { print $4 }' $tmp/log4.out`
if [ "$r" != 1 ]; then
    print_debug "ActionOnPurge on Pool record should be 1"
    bstat=2
fi

print_debug "Test if Media record is ok"
r=`awk '/TestVolume001/ { print $4 }' $tmp/log4.out`
if [ "$r" != 1 ]; then
    print_debug "ActionOnPurge on Media record should be 1"
    bstat=2
fi

end_test
