#!/bin/sh
#
#  Test if Bacula can automatically create a Volume label.
#

TestName="auto-label-test"
JobName=AutoLabel
. scripts/functions

copy_test_confs

echo "${cwd}/build" >${cwd}/tmp/file-list

cp ${cwd}/bin/bacula-dir.conf ${cwd}/tmp/1
sed "s%# Label Format%  Label Format%" ${cwd}/tmp/1 >${cwd}/bin/bacula-dir.conf

change_jobname CompressedTest $JobName
start_test

cat <<END_OF_SCRIPT >${cwd}/tmp/bconcmds
@output /dev/null
messages
@$out ${cwd}/tmp/log1.out
status all
status all
list pools
messages
@#setdebug level=110 storage=File
run job=$JobName storage=File yes
list pools
list volumes
wait
messages
@# 
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select storage=File
unmark *
mark *
count
ls *
dir *
find Makefile
pwd
lsmark
estimate
?
help
done
yes
wait
messages
@$out
quit
END_OF_SCRIPT

run_bacula
check_for_zombie_jobs storage=File || exit 1
stop_bacula

check_two_logs
check_restore_diff
end_test
