#!/bin/sh
#
# Run a simple backup of the Bacula build directory
#   then restore it.
#
cwd=`pwd`
scripts/copy-confs
scripts/cleanup

echo " "
echo " "
echo " === Starting Backup Bacula Test at `date +%R:%S` ==="
echo " === Starting Backup Bacula Test at `date +%R:%S` ===" >>working/log
echo " "

#bin/bacula start 2>&1 >/dev/null
bin/bacula start
bin/bconsole -c bin/bconsole.conf  <<END_OF_DATA 2>&1 >/dev/null
#bin/bconsole -c bin/bconsole.conf  <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
label volume=TestVolume001
run job=Client1 yes
status storage=File
status storage=File
status storage=File
status storage=File
status storage=File
status storage=File
sleep 1
status storage=File
status storage=File
status storage=File
status storage=File
status storage=File
sleep 1
status storage=File
status storage=File
status storage=File
status storage=File
status storage=File
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out  
restore where=${cwd}/tmp/bacula-restores select all done
yes
wait
messages
@output
quit
END_OF_DATA
scripts/check_for_zombie_jobs storage=File
bin/bacula stop 2>&1 >/dev/null
grep "^  Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^  Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! Backup Bacula Test failed!!! !!!!! "
   echo "  !!!!! Backup Bacula Test failed!!! !!!!! " >>test.out
   if [ $bstat != 0 -o $rstat != 0 ] ; then
      echo "  !!!!! Bad Job termination status     !!!!! "
      echo "  !!!!! Bad Job termination status     !!!!! " >>test.out
   else
      echo "  !!!!! Restored files differ          !!!!! "
      echo "  !!!!! Restored files differ          !!!!! " >>test.out
   fi
   echo " "
else
   echo "  ===== Backup Bacula Test OK ===== "
   echo "  ===== Backup Bacula Test OK ===== " >>test.out
   scripts/cleanup
fi
