#!/bin/sh
#
# Run a simple backup of the Bacula build directory
#   then restore it.
#
TestName="backup-bacula-test"
JobName=backup
. scripts/functions
set_debug 0

scripts/copy-confs
scripts/cleanup

start_test

cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@$out tmp/log1.out
label volume=TestVolume001
@#setdebug level=100 storage=File
run job=Client1 yes
status storage=File
status storage=File
status storage=File
status storage=File
status storage=File
status storage=File
@sleep 1
status storage=File
status storage=File
status storage=File
status storage=File
status storage=File
@sleep 1
status storage=File
status storage=File
status storage=File
status storage=File
status storage=File
wait
messages
@# 
@# now do a restore
@#
@$out tmp/log2.out  
restore where=${cwd}/tmp/bacula-restores select all done
yes
wait
messages
@$out
quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storate=File
stop_bacula

check_two_logs
check_restore_diff
end_test
