#!/bin/sh
#
# Run a simple backup of the Bacula build directory
#   then restore it.
#
cwd=`pwd`
scripts/copy-confs
scripts/cleanup
bin/bacula stop 2>&1 >/dev/null
bin/drop_sqlite_tables
bin/make_sqlite_tables

echo " "
echo " "
echo " === Starting Backup Bacula Test ==="
echo " === Starting Backup Bacula Test ===" >>working/log
echo " "

bin/bacula start 2>&1 >/dev/null
bin/bconsole -c bin/bconsole.conf <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
label volume=TestVolume001
run job=Client1 yes
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out  
restore where=${cwd}/tmp/bacula-restores select all
yes
wait
messages
@output
quit
END_OF_DATA
bin/bacula stop 2>&1 >/dev/null
grep "^Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! Backup Bacula Test failed!!! !!!!! "
   echo "  !!!!! Backup Bacula Test failed!!! !!!!! " >>test.out
   echo " "
else
   echo "  ===== Backup Bacula Test OK ===== "
   echo "  ===== Backup Bacula Test OK ===== " >>test.out
   scripts/cleanup
fi
