#!/bin/sh
#
# Run a simple backup of the Bacula build directory 
#   to a tape then restore it.
#
cwd=`pwd`
bin/bacula stop  2>&1 >/dev/null
scripts/copy-tape-confs
scripts/cleanup-tape
echo "${cwd}/build" >/tmp/file-list
bin/drop_sqlite_tables
bin/make_sqlite_tables

echo " "
echo " "
echo " === Starting Bacula tape test ==="
echo " === Starting Bacula tape test ===" >>working/log
echo " "

bin/bacula start 2>&1 >/dev/null
bin/console -c bin/console.conf <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
label storage=DDS-4 volume=TestVolume001 slot=0
run job=NightlySave yes
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select all
yes
wait
messages
@output
quit
END_OF_DATA
bin/bacula stop 2>&1 >/dev/null
grep "^Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! Bacula tape test Bacula source failed!!! !!!!! "
   echo "  !!!!! Bacula tape test failed!!! !!!!! " >>test.out
   echo " "
else
   echo "  ===== Bacula tape test Bacula source OK ===== "
   echo "  ===== Bacula tape test OK ===== " >>test.out
   scripts/cleanup
fi
