#!/bin/sh
#
# Run a simple backup of the Bacula build directory but 
#   split the archive into two volumes, then build a BSR with
#   the restore command and use bextract to restore the files.
#
debug=0
if test "$debug" -eq 1 ; then
  out="tee"
else
  out="output"
fi

cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list

echo " "
echo " "
echo " === Starting bextract-test at `date +%R:%S` ==="
echo " === Starting bextract-test at `date +%R:%S` ===" >working/log
echo " "

cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@$out tmp/log1.out
label storage=File1 volume=TestVolume001
label storage=File1 volume=TestVolume002
update Volume=TestVolume001 MaxVolBytes=3000000
run job=NightlySave storage=File1 yes
wait
messages
@# 
@# now build the bsr file
@#
@$out tmp/log2.out
restore bootstrap=${cwd}/working/restore.bsr where=${cwd}/tmp/bacula-restores select all storage=File1 done
no
wait
messages
@$out
quit
END_OF_DATA

if test "$debug" -eq 1 ; then
  bin/bacula start
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  bin/bacula start 2>&1 >/dev/null
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=File1
bin/bacula stop 2>&1 >/dev/null
mkdir -p ${cwd}/tmp/bacula-restores
exit
bin/bextract -b working/restore.bsr -c bin/bacula-sd.conf ${cwd}/tmp ${cwd}/tmp/bacula-restores 2>&1 >/dev/null
grep "^  Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
diff -r build  tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! bextract-test Bacula source failed!!! !!!!! "
   echo "  !!!!! bextract-test failed!!! !!!!! " >>test.out
   if [ $bstat != 0 ] ; then
      echo "  !!!!! Bad Job termination status     !!!!! "
      echo "  !!!!! Bad Job termination status     !!!!! " >>test.out
   else
      echo "  !!!!! Restored files differ          !!!!! "
      echo "  !!!!! Restored files differ          !!!!! " >>test.out
   fi
   echo " "
else
   echo "  ===== bextract-test Bacula source OK ===== "
   echo "  ===== bextract-test OK ===== " >>test.out
   scripts/cleanup
fi
