#!/bin/sh
#
# Run a simple backup of the Bacula build directory but 
#   split the archive into two volumes, then restore
#   files on only one of the volumes and ensure that
#   the other volume is not used.  I.e. bsr optimization
#   works.
#
cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list

echo " "
echo " "
echo " === Starting bsr-opt-test  ==="
echo " === Starting bsr-opt-test  ===" >working/log
echo " "

bin/bacula start 2>&1 >/dev/null
bin/bconsole -c bin/bconsole.conf <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
label storage=File1 volume=TestVolume001
label storage=File1 volume=TestVolume002
update Volume=TestVolume001 MaxVolBytes=3000000
run job=NightlySave storage=File1 yes
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select storage=File1
unmark *
cd ${cwd}/build/src/cats
mark *
ls
done
yes
wait
messages
@output
quit
END_OF_DATA
scripts/check_for_zombie_jobs storage=File1
bin/bacula stop 2>&1 >/dev/null
#
# This test is not really reliable. What we want to do is
#   to select files on only one Volume, then insure here
#   that only one Volume is chosen.
#
grep TestVolume002 working/restore.bsr 2>&1 >/dev/null
bsrstat=$?
grep "^Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build/src/cats  tmp/bacula-restores${cwd}/build/src/cats 2>&1 >/dev/null
if [ $? != 0 -o $bsrstat != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! bsr-opt-test Bacula source failed!!! !!!!! "
   echo "  !!!!! bsr-opt-test failed!!! !!!!! " >>test.out
   if [ $bstat != 0 -o $rstat != 0 ] ; then
      echo "  !!!!! Bad Job termination status     !!!!! "
      echo "  !!!!! Bad Job termination status     !!!!! " >>test.out
   elif [ $bsrstat != 0 ] ; then
      echo "  !!!!! Volume selection error         !!!!! "
      echo "  !!!!! Volume selection error         !!!!! " >>test.out
   else
      echo "  !!!!! Restored files differ          !!!!! "
      echo "  !!!!! Restored files differ          !!!!! " >>test.out
   fi
   echo " "
else
   echo "  ===== bsr-opt-test Bacula source OK ===== "
   echo "  ===== bsr-opt-test OK ===== " >>test.out
   scripts/cleanup
fi
