#!/bin/sh
#
# Run a simple backup of the Bacula build directory using the compressed option
#   then restore it.
#
cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list
bin/bacula stop  2>&1 >/dev/null
bin/drop_sqlite_tables
bin/make_sqlite_tables

echo " "
echo " "
echo " === Starting compressed-test ==="
echo " === Starting compressed-test ===" >>working/log
echo " "

bin/bacula start
bin/console -c bin/console.conf <<END_OF_DATA
@output /dev/null
messages
@output
label storage=File
TestVolume001
run job=CompressedTest
yes
wait
messages
@# 
@# now do a restore
@#
restore
5
done
yes
wait
@output /dev/null
messages
quit
END_OF_DATA
bin/bacula stop
diff -r build /tmp/bacula-restores${cwd}/build
if [ $? != 0 ] ; then
   echo " "
   echo " "
   echo "  ===== compressed-test Bacula source failed!!! ===== "
   echo "  ===== compressed-test failed!!! ===== " >>test.out
   echo " "
else
   echo "  ===== compressed-test Bacula source OK ===== "
   echo "  ===== compressed-test OK ===== " >>test.out
   scripts/cleanup
fi
