#!/bin/sh
#
# Run eighty jobs at the same time
#
TestName="eighty-simultaneous-jobs-tape"
JobName=EightySimultaneousJobs
. scripts/functions

require_tape_drive

scripts/cleanup-tape
scripts/copy-tape-confs

echo "${cwd}/build" >${cwd}/tmp/file-list

change_jobname $JobName
start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@output /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=DDS-4 volume=TestVolume001 slot=0 pool=Default
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
run job=$JobName level=Full Storage=DDS-4 yes
@sleep 2
status dir
@sleep 5
status dir
status storage=DDS-4
messages
wait
messages
@# 
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select storage=DDS-4
unmark *
mark *
done
yes
wait
messages
@$out
quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=DDS-4
stop_bacula

exit

check_two_logs
check_restore_diff
end_test
