#!/bin/sh
#
#
TestName="eot-fail-tape"
JobName=eotfailtape
. scripts/functions

require_tape_drive

scripts/cleanup-tape
scripts/copy-tape-confs
 
echo "${cwd}/build" >${cwd}/tmp/file-list

out="${cwd}/tmp/sed_tmp"
echo "s%# Maximum File Size%  Maximum File Size%g" >${out}
cp -f ${cwd}/bin/bacula-sd.conf ${cwd}/tmp/1
sed -f ${out} ${cwd}/tmp/1 >${cwd}/bin/bacula-sd.conf

change_jobname $JobName
start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@output /dev/null
messages
@$out tmp/log1.out
label storage=DDS-4 volume=TestVolume001 slot=0 pool=Default
#update Volume=TestVolume001 MaxVolBytes=3000000
run job=$JobName yes
wait
messages
@# 
@# now do a restore
@#
@$out tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select all storage=DDS-4 done
yes
wait
messages
@tee
quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=DDS-4
stop_bacula

check_two_logs
check_restore_diff
end_test
