#!/bin/sh
#
# Run a simple backup of the Bacula build directory 
#   to a tape where we set the minimum and maximum block
#   sizes.
#
debug=0
if test "$debug" -eq 1 ; then
  out="tee"
else
  out="output"
fi
cwd=`pwd`
scripts/copy-tape-confs
scripts/cleanup-tape
echo "${cwd}/build" >/tmp/file-list

cp ${cwd}/bin/bacula-sd.conf ${cwd}/tmp/1
echo "s%# Maximum Block Size%  Maximum Block Size%" >${cwd}/tmp/2
echo "s%# Minimum Block Size%  Minimum Block Size%" >>${cwd}/tmp/2
sed -f ${cwd}/tmp/2 ${cwd}/tmp/1 >${cwd}/bin/bacula-sd.conf
if [ $? != 0 ] ; then
   echo " "
   echo " "
   echo "!!!! sed problem in Fixed Block Size test !!!!!"
   echo " "
   exit 1
fi
rm -f ${cwd}/tmp/1 ${cwd}/tmp/2

echo " "
echo " "
echo " === Starting Fixed Block Size test at `date +%R:%S` ==="
echo " === Starting Fixed Block Size test at `date +%R:%S` ===" >>working/log
echo " "

cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
messages
@$out tmp/log1.out
label storage=DDS-4 volume=TestVolume001 slot=0 pool=Default
run job=NightlySave yes
wait
messages
@# 
@# now do a restore
@#
@$out tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select storage=DDS-4
unmark *
mark *
done
yes
wait
messages
@$out
quit
END_OF_DATA
if test "$debug" -eq 1 ; then
  bin/bacula start
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  bin/bacula start 2>&1 >/dev/null
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi
scripts/check_for_zombie_jobs storage=DDS-4

bin/bacula stop 2>&1 >/dev/null
grep "^  Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^  Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! Fixed Block Size test Bacula source failed!!! !!!!! "
   echo "  !!!!! Fixed Block Size test failed!!! !!!!! " >>test.out
   echo " "
else
   echo "  ===== Fixed Block Size test Bacula source OK ===== "
   echo "  ===== Fixed Block Size test OK ===== " >>test.out
#  scripts/cleanup
fi
