#!/bin/sh
#
# Run two jobs at the same time
#
cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list
bin/bacula stop 2>&1 >/dev/null
bin/drop_sqlite_tables
bin/make_sqlite_tables

echo " "
echo " "
echo " === Starting four-concurrent-jobs-test  ==="
echo " === Starting four-concurrent-jobs-test  ===" >>working/log
echo " "

#bin/bacula start 2>&1 >/dev/null
bin/bacula start
bin/bconsole -c bin/bconsole.conf <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
label storage=File1
TestVolume001
label storage=File1
TestVolume002
update Volume=TestVolume001 MaxVolBytes=100000000
@#50000000
12
run job=NightlySave level=Full Storage=File1
yes
run job=NightlySave level=Full Storage=File1
yes
run job=NightlySave level=Full Storage=File1
yes
run job=NightlySave level=Full Storage=File1
yes
@sleep 2
status dir
@sleep 5
messages
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select all
yes
wait
messages
@output
quit
END_OF_DATA

bin/bacula stop 2>&1 >/dev/null
grep "^Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! four-concurrent-jobs-test Bacula source failed!!! !!!!! "
   echo "  !!!!! four-concurrent-jobs-test failed!!! !!!!! " >>test.out
   echo " "
   exit 1
else
   echo "  ===== four-concurrent-jobs-test Bacula source OK ===== "
   echo "  ===== four-concurrent-jobs-test OK ===== " >>test.out
   scripts/cleanup
   exit 0
fi
