#!/bin/sh
#
# Run a simple backup of the Bacula build directory using the compressed option
#   then backup four times, each with incremental then finally restore.
#   It should require at least 4 different bsrs.
#
debug=0
if test "$debug" -eq 1 ; then
  out="tee"
else
  out="output"
fi

cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list

echo " "
echo " "
echo " === Starting four-jobs-test at `date +%R:%S` ==="
echo " === Starting four-jobs-test at `date +%R:%S` ===" >>working/log
echo " "

cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
estimate job=CompressedTest listing
estimate job=CompressedTest listing
estimate job=CompressedTest listing
messages
@$out tmp/log1.out
label storage=File volume=TestVolume001
run job=CompressedTest yes
wait
messages
quit
END_OF_DATA

if test "$debug" -eq 1 ; then
  bin/bacula start
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  bin/bacula start 2>&1 >/dev/null
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=File
echo "Backup 1 done"
# make some files for the incremental to pick up
touch ${cwd}/build/src/dird/*.c ${cwd}/build/src/dird/*.o
touch ${cwd}/build/src/lib/*.c ${cwd}/build/src/lib/*.o
   
#
# run a second job
#
cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@$out  tmp/log1.out
run job=CompressedTest
yes
wait
messages
quit
END_OF_DATA

if test "$debug" -eq 1 ; then
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=File
echo "Backup 2 done"
touch ${cwd}/build/src/dird/*.c
touch ${cwd}/build/src/lib/*.c ${cwd}/build/src/lib/*.o
#
# run a third job
#
cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@output tmp/log1.out
label storage=File volume=TestVolume001
run job=CompressedTest yes
wait
messages
quit
END_OF_DATA

if test "$debug" -eq 1 ; then
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=File
echo "Backup 3 done"
# make some files for the incremental to pick up
touch ${cwd}/build/src/lib/*.c ${cwd}/build/src/lib/*.o
#
# run a fourth job
#
cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@output tmp/log1.out
label storage=File volume=TestVolume001
run job=CompressedTest yes
wait
messages
quit
END_OF_DATA

if test "$debug" -eq 1 ; then
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=File
echo "Backup 4 done"
# 
# now do several restores to ensure we cleanup between jobs
#
cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
restore where=${cwd}/tmp/bacula-restores select all storage=File done
yes
wait
restore where=${cwd}/tmp/bacula-restores select all storage=File done
yes
wait
@$out tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select storage=File
unmark *
mark *
done
yes
wait
messages
@output
quit
END_OF_DATA

if test "$debug" -eq 1 ; then
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=File
bin/bacula stop 2>&1 >/dev/null
grep "^  Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^  Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! four-jobs-test Bacula source failed!!! !!!!! "
   echo "  !!!!! four-jobs-test failed!!! !!!!! " >>test.out
   if [ $bstat != 0 -o $rstat != 0 ] ; then
      echo "  !!!!! Bad Job termination status     !!!!! "
      echo "  !!!!! Bad Job termination status     !!!!! " >>test.out
   else
      echo "  !!!!! Restored files differ          !!!!! "
      echo "  !!!!! Restored files differ          !!!!! " >>test.out
   fi
   echo " "
else
   echo "  ===== four-jobs-test Bacula source OK ===== "
   echo "  ===== four-jobs-test OK ===== " >>test.out
   scripts/cleanup
fi
