#!/bin/sh
#
# Run four jobs at the same time, with two Volumes.
#   Set max Vol bytes of first volume
#   to less than total backup to force Bacula to use the second
#   Volume.
#
TestName="four-concurrent-jobs-test"
JobName=Four-concurrent-jobs
. scripts/functions

scripts/cleanup
scripts/copy-test-confs
echo "${cwd}/build" >${cwd}/tmp/file-list

change_jobname NightlySave $JobName
start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@output /dev/null
messages
@$out   ${cwd}/tmp/log1.out
label storage=File1
TestVolume001
label storage=File1
TestVolume002
update Volume=TestVolume001 MaxVolBytes=100000000
@#50000000
@#12
setdebug level=51 Storage=File1
status storage=File1
llist volume=TestVolume001
llist volume=TestVolume002
run job=$JobName level=Full Storage=File1
yes
reload
llist volume=TestVolume001
llist volume=TestVolume002
run job=$JobName level=Full Storage=File1
yes
reload
llist volume=TestVolume001
llist volume=TestVolume002
run job=$JobName level=Full Storage=File1
yes
reload
llist volume=TestVolume001
llist volume=TestVolume002
status storage=File1
run job=$JobName level=Full Storage=File1
yes
status storage=File1
reload
reload
reload
reload
@sleep 2
status dir
status storage=File1
llist volume=TestVolume001
llist volume=TestVolume002
reload
@sleep 5
messages
reload
reload
wait
status storage=File1
reload
messages
@# 
@# now do a restore
@#
@$out   ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select storage=File1
unmark *
mark *
done
yes
run job=$JobName level=Full Storage=File1 yes
wait
reload
reload
messages
@output
quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=File1
stop_bacula

check_two_logs
check_restore_diff
end_test
