#!/bin/sh
#
# Run a simple backup of the Bacula build directory then create some           
#   new files, do an Incremental and restore those two files.
#
# This script uses the virtual disk autochanger
#
TestName="incremental-2disk-test"
JobName=Inc2disk
. scripts/functions
set_debug 0

. config.out
if test x${AUTOCHANGER} = x/dev/null ; then
   echo "incremental-2disk test skipped. No autochanger."
   exit
fi

stop_bacula
cd bin
./drop_bacula_tables >/dev/null 2>&1
./make_bacula_tables >/dev/null 2>&1
./grant_bacula_privileges 2>&1 >/dev/null
cd ..

scripts/copy-2disk-confs
scripts/prepare-two-disks

echo "${cwd}/tmp/build" >/tmp/file-list
if test ! -d ${cwd}/tmp/build ; then
   mkdir ${cwd}/tmp/build
fi
cp -p ${cwd}/build/src/dird/*.c ${cwd}/tmp/build
cd ${cwd}/tmp
echo "${cwd}/tmp/build/ficheriro1.txt" >restore-list
echo "${cwd}/tmp/build/ficheriro2.txt" >>restore-list
cd ${cwd}

change_jobname $JobName
start_test

# Write out bconsole commands
cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
messages
@$out tmp/log1.out
label storage=DDS-4 volume=TestVolume001 slot=1 Pool=Default drive=0
label storage=DDS-4 volume=TestVolume002 slot=2 Pool=Default drive=0
run job=$JobName yes
wait
messages
quit
END_OF_DATA

run_bacula

echo "ficheriro1.txt" >${cwd}/tmp/build/ficheriro1.txt
echo "ficheriro2.txt" >${cwd}/tmp/build/ficheriro2.txt


cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
messages
@$out tmp/log1.out
@# Force Incremental on the second Volume
update volume=TestVolume001 VolStatus=Used
run level=Incremental job=$JobName yes
wait
messages
@# 
@# now do a restore
@#
@$out tmp/log2.out
restore where=${cwd}/tmp/bacula-restores 
7
<${cwd}/tmp/restore-list

yes
wait
messages
@$out
quit
END_OF_DATA

run_bconsole

check_for_zombie_jobs storage=File
stop_bacula
#
# Delete .c files because we will only restored the txt files
#
rm -f tmp/build/*.c

check_two_logs
check_restore_tmp_build_diff
end_test
