#!/bin/sh
#
# Run a simple backup of the Bacula build directory then migrate it
#   to another device.
#
# Test migrating a job that spans two Volumes
#
# This script uses the virtual disk autochanger
#
TestName="migration-jobspan-test"
JobName=MigrationJobSpanSave
. scripts/functions


scripts/cleanup
scripts/copy-migration-confs
scripts/prepare-two-disks
echo "${cwd}/build" >${cwd}/tmp/file-list
cp ${cwd}/bin/bacula-sd.conf ${cwd}/tmp/1
sed "s%# Maximum File Size%  Maximum File Size%" ${cwd}/tmp/1 >${cwd}/bin/bacula-sd.conf


change_jobname NightlySave $JobName
start_test

#
# Note, we first backup into Pool Default, 
#          then Migrate into Pool Full. 
#              Pool Default uses Storage=File
#              Pool Full    uses Storage=DiskChanger

# Write out bconsole commands
cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@output
messages
@$out ${cwd}/tmp/log1.out
@#setdebug level=10 dir
@#setdebug level=100 storage=File
label storage=File volume=FileVolume001 Pool=Default
label storage=File volume=FileVolume002 Pool=Default
update Volume=FileVolume001 MaxVolBytes=3000000 pool=Default
label storage=DiskChanger volume=ChangerVolume001 slot=1 Pool=Full drive=0
label storage=DiskChanger volume=ChangerVolume002 slot=2 Pool=Full drive=0
list volumes
@#
run job=$JobName yes
@#run job=$JobName yes
wait
list volumes
@#setdebug level=200 dir
@# should migrate both Volumes
run job=migrate-job yes
wait
purge volume=FileVolume001
purge volume=FileVolume002
list volumes
list jobs
messages
wait
@# 
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select storage=DiskChanger
unmark *
mark *
done
yes
wait
messages
@output
quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=File
stop_bacula

check_two_logs
check_restore_diff
end_test
