#!/bin/sh
#
# Attempt to backup and restore a file with the bpipe plugin
#
TestName="plugin-test"
JobName=pluginTest
. scripts/functions

scripts/cleanup
scripts/copy-plugin-confs
file=encrypt-bug.jpg
echo "${cwd}/${file}" >${cwd}/tmp/file-list

start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@output /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=File1 volume=TestVolume001
setdebug level=50 client=$CLIENT
run job=$JobName storage=File1 yes
wait
messages
quit
END_OF_DATA


run_bacula -d50

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@# 
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
@#setdebug level=50 client=$CLIENT
restore where=${cwd}/tmp  select all storage=File1 done
yes
wait
messages
@$out
quit
END_OF_DATA


run_bconsole

check_for_zombie_jobs storage=File1
stop_bacula

check_two_logs
diff ${cwd}/${file} ${cwd}/tmp/${file}
dstat=$?
end_test
