#!/bin/sh
#
# Run a simple backup of the Bacula build directory using the compressed option
#   then backup four times, each with incremental then finally restore.
#   It should require at least 4 different bsrs.
#
debug=0
if test "$debug" -eq 1 ; then
  out="tee"
else
  out="output"
fi

cwd=`pwd`
scripts/copy-tape-confs
scripts/cleanup-tape
echo "${cwd}/build" >/tmp/file-list

echo " "
echo " "
echo " === Starting relabel-tape at `date +%R:%S` ==="
echo " === Starting relabel-tape at `date +%R:%S` ===" >>working/log
echo " "

cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@$out tmp/log1.out
label storage=DDS-4 volume=TestVolume001 slot=0 pool=Default
run job=NightlySave level=Full yes
wait
messages
add pool=Default
0
TestVolume002
@# set status to append
update volume=TestVolume001
1
.
run job=NightlySave level=Full yes
@sleep 20
unmount
unmount
purge volume=TestVolume001
relabel oldvolume=TestVolume001 volume=TestVolume003 slot=0 pool=Default
list volumes
mount
messages
wait
run job=NightlySave level=Full yes
wait
messages
@$out
quit
END_OF_DATA

if test "$debug" -eq 1 ; then
  bin/bacula start
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  bin/bacula start 2>&1 >/dev/null
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

echo "Backup done"
# 
# now do several restores to ensure we cleanup between jobs
#
cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
restore where=${cwd}/tmp/bacula-restores select all done
yes
wait
restore where=${cwd}/tmp/bacula-restores select all done
yes
wait
@$out tmp/log2.out
@#
@# now unmount the tape and start two restores
@#  at the same time
@#
unmount storage=DDS-4
restore where=${cwd}/tmp/bacula-restores select all done
yes
restore where=${cwd}/tmp/bacula-restores select
unmark *
mark *
done
yes
mount storage=DDS-4
wait
messages
@$out
quit
END_OF_DATA

if test "$debug" -eq 1 ; then
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf
else
  cat tmp/bconcmds | bin/bconsole -c bin/bconsole.conf  2>&1 >/dev/null
fi

scripts/check_for_zombie_jobs storage=DDS-4
bin/bacula stop 2>&1 >/dev/null
grep "^  Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^  Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
dstat=$?
if [ $dstat != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! relabel-tape Bacula source failed!!! !!!!! "
   echo "  !!!!! relabel-tape failed!!! !!!!! " >>test.out
   echo "diff=$dstat backup=$bstat restore=$rstat"
   echo " "
else
   echo "  ===== relabel-tape Bacula source OK ===== "
   echo "  ===== relabel-tape OK ===== " >>test.out
   scripts/cleanup
fi
