#!/bin/sh
#
# Run a simple backup of the Bacula build directory using the compressed option
#   then restore a few selected files.
#
cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list
sed s%\^%${cwd}% ${cwd}/scripts/flist >${cwd}/tmp/restore2-list

echo " "
echo " "
echo " === Starting restore2-by-file-test at `date +%R:%S` ==="
echo " === Starting restore2-by-file-test at `date +%R:%S` ===" >>working/log
echo " "

bin/bacula start 2>&1 >/dev/null
bin/bconsole -c bin/bconsole.conf <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
label storage=File volume=TestVolume001
run job=CompressedTest yes
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out
restore where=${cwd}/tmp/bacula-restores storage=File file=<${cwd}/tmp/restore2-list
yes
wait
messages
@output
quit
END_OF_DATA
scripts/check_for_zombie_jobs storage=File
bin/bacula stop 2>&1 >/dev/null
grep "^  Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^  Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
dstat=0
for i in `cat ${cwd}/tmp/restore2-list`; do  
   diff $i ${cwd}/tmp/bacula-restores$i
   if [ $? != 0 ] ; then
      dstat=1
   fi
done
if [ $dstat != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! restore2-by-file-test Bacula source failed!!! !!!!! "
   echo "  !!!!! restore2-by-file-test failed!!! !!!!! " >>test.out
   echo " "
   echo "Backup term status  = $bstat"
   echo "Restore term status = $rstat"
   echo "Diff status         = $dstat"
   echo " "
else
   echo "  ===== restore2-by-file-test Bacula source OK ===== "
   echo "  ===== restore2-by-file-test OK ===== " >>test.out
   scripts/cleanup
fi
