#!/bin/sh
#
# Create a 60MB file with random bytes. Back it up to 6 Volumes
#   each constrained to 10MB using the automatic labeling feature.
#
TestName="six-vol-test"
JobName=SixVol
. scripts/functions
set_debug 0

if test ! -c /dev/urandom ; then
   echo "No random device. Test skipped.\n"
   exit 0
fi
cwd=`pwd`
scripts/copy-testa-confs
scripts/cleanup
echo "${cwd}/tmp/largefile" >/tmp/file-list
# Create 56MB file with random data
echo "Creating a 56MB file with random data ..."
dd if=/dev/urandom of=${cwd}/tmp/largefile bs=1024 count=55000
echo "largefile created"

start_test

cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@$out tmp/log1.out
run job=MultiVol storage=File yes
wait
messages
@# 
@# now do a restore
@#
@$out tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select storage=File
unmark *
mark *
done
yes
wait
messages
@output
quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=File
stop_bacula

check_two_logs
diff tmp/largefile  tmp/bacula-restores${cwd}/tmp/largefile 2>&1 >/dev/null
dstat=$?
end_test
