#!/bin/sh
#
# Run a simple backup of the Bacula build directory but 
#   split the archive into four volumes, two of which are
#   totally full. I.e. make sure that bsr selects all tapes 
#   including those fully spanned.
#
TestName="span-vol-test"
JobName=SpanVol
. scripts/functions
set_debug 0

cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list
change_jobname $JobName

start_test

cat <<END_OF_DATA >tmp/bconcmds
@output /dev/null
messages
@$out tmp/log1.out
label storage=File1 volume=TestVolume004
label storage=File1 volume=TestVolume003
label storage=File1 volume=TestVolume002
label storage=File1 volume=TestVolume001
update Volume=TestVolume004 MaxVolBytes=3000000
update Volume=TestVolume003 MaxVolBytes=3000000
update Volume=TestVolume002 MaxVolBytes=3000000
run job=$JobName storage=File1 yes
wait
list volumes
messages
@# 
@# now do a restore
@#
@$out tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select storage=File1
unmark *
mark *
done
yes
wait
messages
@$out
quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=File1
stop_bacula

check_two_logs
check_restore_diff
end_test
