#!/bin/sh
#
# Run a simple backup of the Bacula build directory using the Sparse option
#   then restore it.
#
cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list
bin/bacula stop 2>&1 >/dev/null

echo " "
echo " "
echo " === Starting sparse-compressed-test at `date +%R:%S` ==="
echo " === Starting sparse-compressed-test at `date +%R:%S` ===" >>working/log
echo " "

bin/bacula start 2>&1 >/dev/null
bin/bconsole -c bin/bconsole.conf <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
label storage=File volume=TestVolume001
run job=SparseCompressedTest yes
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out   
restore where=${cwd}/tmp/bacula-restores select all storage=File done
yes
wait
messages
@output
quit
END_OF_DATA
scripts/check_for_zombie_jobs storage=File 
bin/bacula stop 2>&1 >/dev/null
grep "^  Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^  Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! sparse-compressed-test Bacula source failed!!! !!!!! "
   echo "  !!!!! sparse-compressed-test failed!!! !!!!! " >>test.out
   if [ $bstat != 0 -o $rstat != 0 ] ; then
      echo "  !!!!! Bad Job termination status     !!!!! "
      echo "  !!!!! Bad Job termination status     !!!!! " >>test.out
   else
      echo "  !!!!! Restored files differ          !!!!! "
      echo "  !!!!! Restored files differ          !!!!! " >>test.out
   fi
   echo " "
else
   echo "  ===== sparse-compressed-test Bacula source OK ===== "
   echo "  ===== sparse-compressed-test OK ===== " >>test.out
   scripts/cleanup
fi
