#!/bin/sh
#
# Run a simple backup of the Bacula build directory using the Sparse option
#   then restore it.
#
TestName="sparse-compressed-test"
JobName=Sparse-conpressed
. scripts/functions

cwd=`pwd`
scripts/cleanup
scripts/copy-test-confs
echo "${cwd}/build" >${cwd}/tmp/file-list

start_test

cat >${cwd}/tmp/bconcmds <<END_OF_DATA
@output /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=File volume=TestVolume001
run job=SparseCompressedTest yes
wait
messages
@# 
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out   
restore where=${cwd}/tmp/bacula-restores select all storage=File done
yes
wait
messages
@output
quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=File 
stop_bacula

check_two_logs
check_restore_diff
end_test
