#!/bin/sh
#
# Run a simple backup of the Bacula build directory using the Sparse option
#   then restore it.
#
cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list
bin/bacula stop 2>&1 >/dev/null
bin/drop_sqlite_tables
bin/make_sqlite_tables

echo " "
echo " "
echo " === Starting sparse-test ==="
echo " === Starting sparse-test ===" >>working/log
echo " "

bin/bacula start
bin/console -c bin/console.conf <<END_OF_DATA
messages
@output tmp/log2.out
label storage=File
TestVolume001
run job=SparseTest
yes
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out
restore
5
done
yes
wait
messages
quit
END_OF_DATA
bin/bacula stop 2>&1 >/dev/null
grep "^Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build /tmp/bacula-restores${cwd}/build
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  ===== sparse-test Bacula source failed!!! ===== "
   echo "  ===== sparse-test failed!!! ===== " >>test.out
   echo " "
else
   echo "  ===== sparse-test Bacula source OK ===== "
   echo "  ===== sparse-test OK ===== " >>test.out
   scripts/cleanup
fi
