#!/bin/sh
#
# Run a simple backup with encryption and a real sparse file.
#
TestName="sparse-encrypt-test"
JobName=Crypto
. scripts/functions
set_debug 0

scripts/cleanup
scripts/copy-crypto-confs
echo "${cwd}/build" >/tmp/file-list
cd ${cwd}/build/src/tools
./gigaslam
if [ $? != 0 ]; then
   echo "Execute of ${cwd}/build/src/tools/gigaslam failed."
   rm -f ${cwd}/build/src/tools/gigaslam.gif
   exit 1
fi
cd ${cwd}

start_test

cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
messages
@$out tmp/log1.out
label storage=File volume=TestVolume001
setdebug level=10 fd
run job=$JobName yes
wait
messages
list volumes
@# 
@# now do a restore
@#
@$out tmp/log2.out
@# setdebug level=0 fd
restore where=${cwd}/tmp/bacula-restores storage=File
5
mark *
done
yes
wait
messages
@$out
quit
END_OF_DATA

run_bacula
sleep 2
check_for_zombie_jobs storage=File 
stop_bacula

size=`du ${cwd}/tmp/bacula-restores/${cwd}/build/src/tools/gigaslam.gif | cut -f 1`
if [ $size -gt 120 ]; then
   echo "========== restored sparse file: gigaslam.gif too big ========="
   echo "      size is ${size}K it should be 120K"
fi

check_two_logs
check_restore_diff
end_test
rm -f ${cwd}/build/src/tools/gigaslam.gif
