#!/bin/sh
#
# Run a simple backup of the Bacula build directory using the Sparse option
#   then restore it.
#
TestName="sparse-test"
JobName=SparseTest
. scripts/functions
set_debug 0

cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list

start_test

cat >tmp/bconcmds <<END_OF_DATA
@output /dev/null
messages
@$out tmp/log1.out
label storage=File volume=TestVolume001
run job=$JobName yes
wait
messages
@# 
@# now do a restore
@#
@$out tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select storage=File
unmark *
mark *
done
yes
wait
messages
@output
quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=File 
stop_bacula

check_two_logs
check_restore_diff
end_test
