#!/bin/sh
#
# Attempt to strip the path
#
TestName="strip-test"
JobName=stripTest
. scripts/functions

scripts/cleanup
scripts/copy-strip-confs


echo "${cwd}/build/src/dird" >${cwd}/tmp/file-list

change_jobname NightlySave $JobName
start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@$out ${cwd}/tmp/log1.out
@#setdebug level=150 dir
@#setdebug level=150 storage=FileStorage
setdebug level=100 client
label storage=FileStorage pool=Default volume=TestVolume001
run job=$JobName storage=FileStorage pool=Default yes
wait
messages
quit
END_OF_DATA


run_bacula

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@$out /dev/null
messages
@# 
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
@#setdebug level=50 client
restore where=${cwd}/tmp/bacula-restores select all storage=FileStorage done
yes
wait
messages
@$out
quit
END_OF_DATA

run_bconsole

check_for_zombie_jobs storage=FileStorage
stop_bacula

check_two_logs
# check_restore_diff does not work because we cannot read all /etc, so skip it
dstat=0
end_test
