#!/bin/sh
#
# Run a simple backup of the Bacula build directory using the compressed option
#   then backup a second time and finally restore it
#
cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list
bin/bacula stop 2>&1 >/dev/null
cd bin
./drop_bacula_tables >/dev/null 2>&1
./make_bacula_tables >/dev/null 2>&1
./grant_bacula_privileges 2>&1 >/dev/null
cd ..

echo " "
echo " "
echo " === Starting two-jobs-test  ==="
echo " === Starting two-jobs-test  ===" >>working/log
echo " "

bin/bacula start 2>&1 >/dev/null
bin/bconsole -c bin/bconsole.conf <<END_OF_DATA
@output /dev/null
estimate job=CompressedTest listing
estimate job=CompressedTest listing
estimate job=CompressedTest listing
messages
@output tmp/log1.out
label storage=File volume=TestVolume001
run job=CompressedTest yes
wait
messages
quit
END_OF_DATA
echo "Backup 1 done"
touch ${cwd}/build/src/dird/*.c
#
# run a second job
#
bin/bconsole -c bin/bconsole.conf <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
run job=CompressedTest
yes
wait
messages
@# 
@# now do several restores to ensure we cleanup between jobs
@#
@output /dev/null
restore where=${cwd}/tmp/bacula-restores select all
yes
wait
restore where=${cwd}/tmp/bacula-restores select all
yes
wait
@output tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select all
yes
wait
messages
@output
quit
END_OF_DATA
bin/bacula stop 2>&1 >/dev/null
grep "^Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! two-jobs-test Bacula source failed!!! !!!!! "
   echo "  !!!!! two-jobs-test failed!!! !!!!! " >>test.out
   echo " "
else
   echo "  ===== two-jobs-test Bacula source OK ===== "
   echo "  ===== two-jobs-test OK ===== " >>test.out
   scripts/cleanup
fi
