#!/bin/sh
#
# Run a simple backup of the Bacula build directory using the compressed option
#   then backup a second time and finally restore it
#
cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list
bin/bacula stop 2>&1 >/dev/null
bin/drop_sqlite_tables
bin/make_sqlite_tables

echo " "
echo " "
echo " === Starting two-jobs-test  ==="
echo " === Starting two-jobs-test  ===" >>working/log
echo " "

bin/bacula start 2>&1 >/dev/null
bin/console -c bin/console.conf <<END_OF_DATA
messages
@output tmp/log1.out
label storage=File
TestVolume001
run job=CompressedTest
yes
wait
messages
quit
END_OF_DATA
echo "Backup 1 done"
touch ${cwd}/build/src/dird/*.c
#
# run a second job
#
bin/console -c bin/console.conf <<END_OF_DATA
messages
@output tmp/log1.out
run job=CompressedTest
yes
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out
restore
5
done
yes
wait
messages
quit
END_OF_DATA
bin/bacula stop 2>&1 >/dev/null
diff -r build /tmp/bacula-restores${cwd}/build
if [ $? != 0 ] ; then
   echo " "
   echo " "
   echo "  ===== two-jobs-test Bacula source failed!!! ===== "
   echo "  ===== two-jobs-test failed!!! ===== " >>test.out
   echo " "
else
   echo "  ===== two-jobs-test Bacula source OK ===== "
   echo "  ===== two-jobs-test OK ===== " >>test.out
   scripts/cleanup
fi
