#!/bin/sh
#
# Run a simple backup of the Bacula build directory but 
#   split the archive into two volumes
#
cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/build" >/tmp/file-list

echo " "
echo " "
echo " === Starting two-vol-test at `date +%R:%S` ==="
echo " === Starting two-vol-test at `date +%R:%S` ===" >working/log
echo " "

bin/bacula start 2>&1 >/dev/null
# bin/bacula start
bin/bconsole -c bin/bconsole.conf <<END_OF_DATA 2>&1 >/dev/null
#bin/bconsole -c bin/bconsole.conf <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
label storage=File1 volume=TestVolume001
label storage=File1 volume=TestVolume002
update Volume=TestVolume001 MaxVolBytes=3000000
run job=NightlySave storage=File1 yes
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select all storage=File1 done
yes
wait
messages
@output
quit
END_OF_DATA
scripts/check_for_zombie_jobs storage=File1
bin/bacula stop 2>&1 >/dev/null
grep "^  Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^  Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff -r build  tmp/bacula-restores${cwd}/build 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! two-vol-test Bacula source failed!!! !!!!! "
   echo "  !!!!! two-vol-test failed!!! !!!!! " >>test.out
   if [ $bstat != 0 -o $rstat != 0 ] ; then
      echo "  !!!!! Bad Job termination status     !!!!! "
      echo "  !!!!! Bad Job termination status     !!!!! " >>test.out
   else
      echo "  !!!!! Restored files differ          !!!!! "
      echo "  !!!!! Restored files differ          !!!!! " >>test.out
   fi
   echo " "
else
   echo "  ===== two-vol-test Bacula source OK ===== "
   echo "  ===== two-vol-test OK ===== " >>test.out
   scripts/cleanup
fi
