#!/bin/sh
#
# Run a simple backup of the Bacula build directory
#   then verify the catalog.           
#
TestName="verify-vol-test"
JobName=VerifyVol
. scripts/functions

cwd=`pwd`
scripts/cleanup
scripts/copy-test-confs
echo "${cwd}/build" >${cwd}/tmp/file-list

change_jobname NightlySave $JobName
start_test

cat <<END_OF_DATA >tmp/bconcmds
@$out /dev/null
messages
@$out tmp/log1.out
setdebug level=1 storage=File sd
label storage=File volume=TestVolume001
run job=$JobName yes
wait
messages
@# 
@# now do a verify volume
@#
@$out ${cwd}/tmp/original
setdebug level=12 dir
run job=VerifyVolume
yes
wait
messages
@$out
quit
END_OF_DATA

run_bacula

sleep 2
check_for_zombie_jobs storage=File 
stop_bacula

grep "^  Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^  Termination: *Verify OK" ${cwd}/tmp/original 2>&1 >/dev/null
rstat=$?
dstat=0
end_test
