#!/bin/sh
#
# Run a simple backup of the Bacula build directory
#   then restore it.
#
if test ! -d weird-files ; then
   echo " "
   echo "Weird files not configured. Test not run."
   exit 0
fi
cwd=`pwd`
scripts/copy-test-confs
scripts/cleanup
echo "${cwd}/weird-files" >/tmp/file-list
bin/bacula stop 2>&1 >/dev/null
bin/drop_sqlite_tables
bin/make_sqlite_tables

echo " "
echo " "
echo " === Starting weird filenames test ==="
echo " === Starting weird filenames test ===" >>working/log
echo " "

bin/bacula start 2>&1 >/dev/null
bin/bconsole -c bin/bconsole.conf <<END_OF_DATA
@output /dev/null
messages
@output tmp/log1.out
label storage=File
TestVolume001
run job=NightlySave
yes
wait
messages
@# 
@# now do a restore
@#
@output tmp/log2.out
restore where=${cwd}/tmp/bacula-restores select all
yes
wait
messages
@output
quit
END_OF_DATA
bin/bacula stop 2>&1 >/dev/null
${cwd}/bin/testls weird-files >${cwd}/tmp/original
cd tmp/bacula-restores${cwd}
${cwd}/bin/testls weird-files >${cwd}/tmp/restored
cd ${cwd}
grep "^Termination: *Backup OK" tmp/log1.out 2>&1 >/dev/null
bstat=$?
grep "^Termination: *Restore OK" tmp/log2.out 2>&1 >/dev/null
rstat=$?
diff ${cwd}/tmp/original ${cwd}/tmp/restored 2>&1 >/dev/null
if [ $? != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
   echo " "
   echo " "
   echo "  !!!!! Weird files test failed!!! !!!!! "
   echo "  !!!!! Weird files test failed!!! !!!!! " >>test.out
   echo " "
else
   echo "  ===== Weird files test OK ===== "
   echo "  ===== Weird files test OK ===== " >>test.out
   cd ${cwd}
   scripts/cleanup
fi
