/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo file1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Connect"),
    N_("Connect to Director"),
    (gpointer) on_connect_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Disconnect"),
    N_("Disconnect from Director"),
    (gpointer) on_disconnect_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("gtk-quit"),
    NULL,
    (gpointer) on_exit_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo edit1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("gtk-cut"),
    NULL,
    (gpointer) on_cut1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("gtk-copy"),
    NULL,
    (gpointer) on_copy1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("gtk-paste"),
    NULL,
    (gpointer) on_paste1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("gtk-clear"),
    NULL,
    (gpointer) on_clear1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo item1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Display Messages"),
    NULL,
    (gpointer) on_msgs_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo settings1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("gtk-preferences"),
    NULL,
    (gpointer) on_preferences1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("gnome-stock-about"),
    NULL,
    (gpointer) on_about_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_File"),
    NULL,
    file1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Edit"),
    NULL,
    edit1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_View"),
    N_("Display Messages"),
    item1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Settings"),
    NULL,
    settings1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Help"),
    NULL,
    help1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_app1 (void)
{
  GtkWidget *app1;
  GtkWidget *vbox6;
  GtkWidget *handlebox1;
  GtkWidget *menubar1;
  GtkWidget *handlebox2;
  GtkWidget *toolbar2;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *connect_button1;
  GtkWidget *run_button1;
  GtkWidget *msgs_button;
  GtkWidget *restore_button;
  GtkWidget *label_button;
  GtkWidget *vbox7;
  GtkWidget *scrolledwindow3;
  GtkWidget *text1;
  GtkWidget *hbox18;
  GtkWidget *label38;
  GtkWidget *entry1;
  GtkWidget *hbox19;
  GtkWidget *frame1;
  GtkWidget *label39;
  GtkWidget *frame2;
  GtkWidget *status1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  app1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (app1), _("Bacula Console"));

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (app1), vbox6);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox6), handlebox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (handlebox1), 1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), menubar1);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox6), handlebox2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (handlebox2), 1);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_show (toolbar2);
  gtk_container_add (GTK_CONTAINER (handlebox2), toolbar2);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar2), 1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_BOTH);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-new", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2)));
  connect_button1 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Connect"),
                                _("Connect to Director"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (connect_button1);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-execute", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2)));
  run_button1 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Run"),
                                _("Run a Job"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (run_button1);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-find", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2)));
  msgs_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Msgs"),
                                _("Display Messages"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (msgs_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-revert-to-saved", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2)));
  restore_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Restore"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (restore_button);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-save-as", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2)));
  label_button = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar2),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Label"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar2)->children)->data))->label), TRUE);
  gtk_widget_show (label_button);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), vbox7, TRUE, TRUE, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox7), scrolledwindow3, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow3, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  text1 = gtk_text_view_new ();
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), text1);
  GTK_WIDGET_UNSET_FLAGS (text1, GTK_CAN_FOCUS);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (text1), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (text1), GTK_WRAP_WORD);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox18, FALSE, TRUE, 0);

  label38 = gtk_label_new (_(" Command: "));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox18), label38, FALSE, TRUE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox18), entry1, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (entry1, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, entry1, _("Enter Commands Here"), NULL);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox19, FALSE, FALSE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox19), frame1, FALSE, TRUE, 0);

  label39 = gtk_label_new (_(" Status: "));
  gtk_widget_show (label39);
  gtk_container_add (GTK_CONTAINER (frame1), label39);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox19), frame2, TRUE, TRUE, 0);

  status1 = gtk_label_new ("");
  gtk_widget_show (status1);
  gtk_container_add (GTK_CONTAINER (frame2), status1);
  gtk_label_set_justify (GTK_LABEL (status1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (status1), 0, 0.5);

  g_signal_connect ((gpointer) app1, "delete_event",
                    G_CALLBACK (on_app1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) connect_button1, "clicked",
                    G_CALLBACK (on_connect_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) run_button1, "clicked",
                    G_CALLBACK (on_run_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) msgs_button, "clicked",
                    G_CALLBACK (on_msgs_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) restore_button, "clicked",
                    G_CALLBACK (on_restore_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) label_button, "clicked",
                    G_CALLBACK (on_label_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) entry1, "key_press_event",
                    G_CALLBACK (on_entry1_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) entry1, "key_release_event",
                    G_CALLBACK (on_entry1_key_release_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (app1, app1, "app1");
  GLADE_HOOKUP_OBJECT (app1, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (app1, handlebox1, "handlebox1");
  GLADE_HOOKUP_OBJECT (app1, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (app1, menubar1_uiinfo[0].widget, "file1");
  GLADE_HOOKUP_OBJECT (app1, file1_menu_uiinfo[0].widget, "connect1");
  GLADE_HOOKUP_OBJECT (app1, file1_menu_uiinfo[1].widget, "disconnect1");
  GLADE_HOOKUP_OBJECT (app1, file1_menu_uiinfo[2].widget, "menuitem4");
  GLADE_HOOKUP_OBJECT (app1, file1_menu_uiinfo[3].widget, "exit1");
  GLADE_HOOKUP_OBJECT (app1, menubar1_uiinfo[1].widget, "edit1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[0].widget, "cut1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[1].widget, "copy1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[2].widget, "paste1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[3].widget, "clear1");
  GLADE_HOOKUP_OBJECT (app1, edit1_menu_uiinfo[4].widget, "separator1");
  GLADE_HOOKUP_OBJECT (app1, menubar1_uiinfo[2].widget, "item1");
  GLADE_HOOKUP_OBJECT (app1, item1_menu_uiinfo[0].widget, "msgs");
  GLADE_HOOKUP_OBJECT (app1, menubar1_uiinfo[3].widget, "settings1");
  GLADE_HOOKUP_OBJECT (app1, settings1_menu_uiinfo[0].widget, "preferences1");
  GLADE_HOOKUP_OBJECT (app1, menubar1_uiinfo[4].widget, "help1");
  GLADE_HOOKUP_OBJECT (app1, help1_menu_uiinfo[0].widget, "about1");
  GLADE_HOOKUP_OBJECT (app1, handlebox2, "handlebox2");
  GLADE_HOOKUP_OBJECT (app1, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (app1, connect_button1, "connect_button1");
  GLADE_HOOKUP_OBJECT (app1, run_button1, "run_button1");
  GLADE_HOOKUP_OBJECT (app1, msgs_button, "msgs_button");
  GLADE_HOOKUP_OBJECT (app1, restore_button, "restore_button");
  GLADE_HOOKUP_OBJECT (app1, label_button, "label_button");
  GLADE_HOOKUP_OBJECT (app1, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (app1, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (app1, text1, "text1");
  GLADE_HOOKUP_OBJECT (app1, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (app1, label38, "label38");
  GLADE_HOOKUP_OBJECT (app1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (app1, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (app1, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (app1, label39, "label39");
  GLADE_HOOKUP_OBJECT (app1, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (app1, status1, "status1");
  GLADE_HOOKUP_OBJECT_NO_REF (app1, tooltips, "tooltips");

  gtk_widget_grab_focus (entry1);
  gtk_widget_grab_default (entry1);
  return app1;
}

GtkWidget*
create_about1 (void)
{
  GtkWidget *about1;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox8;
  GtkWidget *vbox9;
  GtkWidget *about_head;
  GtkWidget *hseparator1;
  GtkWidget *copyright;
  GtkWidget *authors;
  GtkWidget *theme;
  GtkWidget *dialog_action_area5;
  GtkWidget *hbox20;
  GtkWidget *label44;
  GtkWidget *about_button;

  about1 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (about1), _("About Bacula Console"));
  gtk_window_set_modal (GTK_WINDOW (about1), TRUE);

  dialog_vbox5 = GTK_DIALOG (about1)->vbox;
  gtk_widget_show (dialog_vbox5);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox8, TRUE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox9, TRUE, TRUE, 0);

  about_head = gtk_label_new (_("Bacula Console 1.19 (28 April 2002)\n"));
  gtk_widget_show (about_head);
  gtk_box_pack_start (GTK_BOX (vbox9), about_head, FALSE, FALSE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox9), hseparator1, FALSE, FALSE, 0);

  copyright = gtk_label_new (_("Copyright (c) 1999 - 2002, Kern Sibbald and John Walker"));
  gtk_widget_show (copyright);
  gtk_box_pack_start (GTK_BOX (vbox9), copyright, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (copyright), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (copyright), 0.1, 0.5);

  authors = gtk_label_new (_("Authors: Kern Sibbald and John Walker"));
  gtk_widget_show (authors);
  gtk_box_pack_start (GTK_BOX (vbox9), authors, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (authors), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (authors), 0.0400001, 0.5);

  theme = gtk_label_new (_("It comes by night and sucks the essence from your computers"));
  gtk_widget_show (theme);
  gtk_box_pack_start (GTK_BOX (vbox9), theme, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (theme), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (theme), 0.15, 0.5);

  dialog_action_area5 = GTK_DIALOG (about1)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (dialog_action_area5), hbox20);

  label44 = gtk_label_new ("");
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox20), label44, TRUE, FALSE, 0);

  about_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (about_button);
  gtk_box_pack_start (GTK_BOX (hbox20), about_button, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (about_button), 1);
  GTK_WIDGET_SET_FLAGS (about_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) about_button, "clicked",
                    G_CALLBACK (on_about_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about1, about1, "about1");
  GLADE_HOOKUP_OBJECT_NO_REF (about1, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (about1, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (about1, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (about1, about_head, "about_head");
  GLADE_HOOKUP_OBJECT (about1, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (about1, copyright, "copyright");
  GLADE_HOOKUP_OBJECT (about1, authors, "authors");
  GLADE_HOOKUP_OBJECT (about1, theme, "theme");
  GLADE_HOOKUP_OBJECT_NO_REF (about1, dialog_action_area5, "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (about1, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (about1, label44, "label44");
  GLADE_HOOKUP_OBJECT (about1, about_button, "about_button");

  return about1;
}

GtkWidget*
create_SelectDirectorDialog (void)
{
  GtkWidget *SelectDirectorDialog;
  GtkWidget *dialog_vbox6;
  GtkWidget *vbox10;
  GtkWidget *label48;
  GtkWidget *label47;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *dirselect;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbox21;
  GtkWidget *button11;
  GtkWidget *label46;
  GtkWidget *button13;

  SelectDirectorDialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (SelectDirectorDialog), _("Select Director"));
  gtk_window_set_modal (GTK_WINDOW (SelectDirectorDialog), TRUE);

  dialog_vbox6 = GTK_DIALOG (SelectDirectorDialog)->vbox;
  gtk_widget_show (dialog_vbox6);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), vbox10, TRUE, TRUE, 0);

  label48 = gtk_label_new ("");
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (vbox10), label48, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label48), 0.48, 0.46);

  label47 = gtk_label_new (_("Select Director"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (vbox10), label47, FALSE, FALSE, 0);

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (vbox10), combo1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (combo1), 6);
  combo1_items = g_list_append (combo1_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  dirselect = GTK_COMBO (combo1)->entry;
  gtk_widget_show (dirselect);

  dialog_action_area2 = GTK_DIALOG (SelectDirectorDialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (dialog_action_area2), hbox21);

  button11 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button11);
  gtk_box_pack_start (GTK_BOX (hbox21), button11, FALSE, FALSE, 0);

  label46 = gtk_label_new (_("         "));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox21), label46, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label46), 2, 0);

  button13 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button13);
  gtk_box_pack_start (GTK_BOX (hbox21), button13, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_select_director_OK_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_select_director_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SelectDirectorDialog, SelectDirectorDialog, "SelectDirectorDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (SelectDirectorDialog, dialog_vbox6, "dialog_vbox6");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, label48, "label48");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, label47, "label47");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, dirselect, "dirselect");
  GLADE_HOOKUP_OBJECT_NO_REF (SelectDirectorDialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, button11, "button11");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, label46, "label46");
  GLADE_HOOKUP_OBJECT (SelectDirectorDialog, button13, "button13");

  return SelectDirectorDialog;
}

GtkWidget*
create_RunDialog (void)
{
  GtkWidget *RunDialog;
  GtkWidget *dialog_vbox7;
  GtkWidget *vbox11;
  GtkWidget *vbox12;
  GtkWidget *label62;
  GtkWidget *hbox28;
  GtkWidget *hbox29;
  GtkWidget *label63;
  GtkWidget *combo_job;
  GList *combo_job_items = NULL;
  GtkWidget *entry_job;
  GtkWidget *label64;
  GtkWidget *combo_type;
  GList *combo_type_items = NULL;
  GtkWidget *entry_type;
  GtkWidget *label65;
  GtkWidget *hbox30;
  GtkWidget *label66;
  GtkWidget *combo_client;
  GList *combo_client_items = NULL;
  GtkWidget *entry_client;
  GtkWidget *label67;
  GtkWidget *hbox31;
  GtkWidget *label68;
  GtkWidget *combo_fileset;
  GList *combo_fileset_items = NULL;
  GtkWidget *entry_fileset;
  GtkWidget *view_fileset_button;
  GtkWidget *label69;
  GtkWidget *hbox32;
  GtkWidget *label70;
  GtkWidget *combo_level;
  GList *combo_level_items = NULL;
  GtkWidget *entry_level;
  GtkWidget *label71;
  GtkWidget *hbox33;
  GtkWidget *label72;
  GtkWidget *combo_pool;
  GList *combo_pool_items = NULL;
  GtkWidget *entry_pool;
  GtkWidget *label73;
  GtkWidget *hbox39;
  GtkWidget *label96;
  GtkWidget *combo_storage;
  GList *combo_storage_items = NULL;
  GtkWidget *entry_storage;
  GtkWidget *label97;
  GtkWidget *hbox40;
  GtkWidget *label98;
  GtkWidget *combo_messages;
  GList *combo_messages_items = NULL;
  GtkWidget *entry_messages;
  GtkWidget *label99;
  GtkWidget *hbox34;
  GtkWidget *label77;
  GtkWidget *entry_where;
  GtkWidget *label78;
  GtkWidget *hbox41;
  GtkWidget *label100;
  GtkWidget *entry_when;
  GtkWidget *label101;
  GtkWidget *label84;
  GtkWidget *dialog_action_area6;
  GtkWidget *hbuttonbox1;
  GtkWidget *run_ok;
  GtkWidget *run_cancel;

  RunDialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (RunDialog), _("Run a Job"));

  dialog_vbox7 = GTK_DIALOG (RunDialog)->vbox;
  gtk_widget_show (dialog_vbox7);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (dialog_vbox7), vbox11, TRUE, TRUE, 0);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (vbox11), vbox12, TRUE, TRUE, 0);

  label62 = gtk_label_new (_("Run a Job"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (vbox12), label62, FALSE, FALSE, 2);
  gtk_misc_set_padding (GTK_MISC (label62), 0, 9);

  hbox28 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox28);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox28, FALSE, FALSE, 2);

  hbox29 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox29);
  gtk_box_pack_start (GTK_BOX (hbox28), hbox29, TRUE, TRUE, 0);

  label63 = gtk_label_new (_("Job:"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox29), label63, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label63), GTK_JUSTIFY_RIGHT);

  combo_job = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_job)->popwin),
                     "GladeParentKey", combo_job);
  gtk_widget_show (combo_job);
  gtk_box_pack_start (GTK_BOX (hbox29), combo_job, TRUE, TRUE, 1);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_job), TRUE, FALSE);
  combo_job_items = g_list_append (combo_job_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_job), combo_job_items);
  g_list_free (combo_job_items);

  entry_job = GTK_COMBO (combo_job)->entry;
  gtk_widget_show (entry_job);
  gtk_editable_set_editable (GTK_EDITABLE (entry_job), FALSE);

  label64 = gtk_label_new (_("   Type:"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox29), label64, FALSE, FALSE, 0);

  combo_type = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_type)->popwin),
                     "GladeParentKey", combo_type);
  gtk_widget_show (combo_type);
  gtk_box_pack_start (GTK_BOX (hbox29), combo_type, FALSE, FALSE, 6);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_type), TRUE, FALSE);
  combo_type_items = g_list_append (combo_type_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_type), combo_type_items);
  g_list_free (combo_type_items);

  entry_type = GTK_COMBO (combo_type)->entry;
  gtk_widget_show (entry_type);
  gtk_editable_set_editable (GTK_EDITABLE (entry_type), FALSE);

  label65 = gtk_label_new (_(" "));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox28), label65, FALSE, FALSE, 30);

  hbox30 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox30);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox30, TRUE, TRUE, 0);

  label66 = gtk_label_new (_("Client:"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox30), label66, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label66), GTK_JUSTIFY_RIGHT);

  combo_client = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_client)->popwin),
                     "GladeParentKey", combo_client);
  gtk_widget_show (combo_client);
  gtk_box_pack_start (GTK_BOX (hbox30), combo_client, TRUE, TRUE, 1);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_client), TRUE, FALSE);
  combo_client_items = g_list_append (combo_client_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_client), combo_client_items);
  g_list_free (combo_client_items);

  entry_client = GTK_COMBO (combo_client)->entry;
  gtk_widget_show (entry_client);
  gtk_editable_set_editable (GTK_EDITABLE (entry_client), FALSE);

  label67 = gtk_label_new (_(" "));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox30), label67, FALSE, FALSE, 123);

  hbox31 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox31);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox31, TRUE, TRUE, 2);

  label68 = gtk_label_new (_("FileSet: "));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox31), label68, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label68), GTK_JUSTIFY_RIGHT);

  combo_fileset = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_fileset)->popwin),
                     "GladeParentKey", combo_fileset);
  gtk_widget_show (combo_fileset);
  gtk_box_pack_start (GTK_BOX (hbox31), combo_fileset, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_fileset), TRUE, FALSE);
  combo_fileset_items = g_list_append (combo_fileset_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_fileset), combo_fileset_items);
  g_list_free (combo_fileset_items);

  entry_fileset = GTK_COMBO (combo_fileset)->entry;
  gtk_widget_show (entry_fileset);
  gtk_editable_set_editable (GTK_EDITABLE (entry_fileset), FALSE);

  view_fileset_button = gtk_button_new_with_mnemonic (_("  View FileSet  "));
  gtk_widget_show (view_fileset_button);
  gtk_box_pack_start (GTK_BOX (hbox31), view_fileset_button, FALSE, TRUE, 10);

  label69 = gtk_label_new (_("  "));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox31), label69, FALSE, FALSE, 65);

  hbox32 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox32);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox32, TRUE, TRUE, 2);

  label70 = gtk_label_new (_("Level:"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox32), label70, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label70), GTK_JUSTIFY_RIGHT);

  combo_level = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_level)->popwin),
                     "GladeParentKey", combo_level);
  gtk_widget_show (combo_level);
  gtk_box_pack_start (GTK_BOX (hbox32), combo_level, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_level), TRUE, FALSE);
  combo_level_items = g_list_append (combo_level_items, (gpointer) "");
  combo_level_items = g_list_append (combo_level_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_level), combo_level_items);
  g_list_free (combo_level_items);

  entry_level = GTK_COMBO (combo_level)->entry;
  gtk_widget_show (entry_level);
  gtk_editable_set_editable (GTK_EDITABLE (entry_level), FALSE);

  label71 = gtk_label_new (_("             "));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox32), label71, FALSE, FALSE, 100);

  hbox33 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox33);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox33, TRUE, TRUE, 2);

  label72 = gtk_label_new (_("Pool:"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox33), label72, FALSE, FALSE, 0);

  combo_pool = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_pool)->popwin),
                     "GladeParentKey", combo_pool);
  gtk_widget_show (combo_pool);
  gtk_box_pack_start (GTK_BOX (hbox33), combo_pool, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_pool), TRUE, FALSE);
  combo_pool_items = g_list_append (combo_pool_items, (gpointer) "");
  combo_pool_items = g_list_append (combo_pool_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_pool), combo_pool_items);
  g_list_free (combo_pool_items);

  entry_pool = GTK_COMBO (combo_pool)->entry;
  gtk_widget_show (entry_pool);
  gtk_editable_set_editable (GTK_EDITABLE (entry_pool), FALSE);

  label73 = gtk_label_new (_("   "));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox33), label73, FALSE, FALSE, 120);

  hbox39 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox39);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox39, TRUE, TRUE, 0);

  label96 = gtk_label_new (_("Storage:"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox39), label96, FALSE, FALSE, 0);

  combo_storage = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_storage)->popwin),
                     "GladeParentKey", combo_storage);
  gtk_widget_show (combo_storage);
  gtk_box_pack_start (GTK_BOX (hbox39), combo_storage, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_storage), TRUE, FALSE);
  combo_storage_items = g_list_append (combo_storage_items, (gpointer) "");
  combo_storage_items = g_list_append (combo_storage_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_storage), combo_storage_items);
  g_list_free (combo_storage_items);

  entry_storage = GTK_COMBO (combo_storage)->entry;
  gtk_widget_show (entry_storage);
  gtk_editable_set_editable (GTK_EDITABLE (entry_storage), FALSE);

  label97 = gtk_label_new (_("   "));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox39), label97, FALSE, FALSE, 120);

  hbox40 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox40);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox40, TRUE, TRUE, 0);

  label98 = gtk_label_new (_("Messages:"));
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (hbox40), label98, FALSE, FALSE, 0);

  combo_messages = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_messages)->popwin),
                     "GladeParentKey", combo_messages);
  gtk_widget_show (combo_messages);
  gtk_box_pack_start (GTK_BOX (hbox40), combo_messages, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_messages), TRUE, FALSE);
  combo_messages_items = g_list_append (combo_messages_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_messages), combo_messages_items);
  g_list_free (combo_messages_items);

  entry_messages = GTK_COMBO (combo_messages)->entry;
  gtk_widget_show (entry_messages);
  gtk_editable_set_editable (GTK_EDITABLE (entry_messages), FALSE);

  label99 = gtk_label_new (_("   "));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox40), label99, FALSE, FALSE, 120);

  hbox34 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox34);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox34, TRUE, TRUE, 2);

  label77 = gtk_label_new (_("Where: "));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox34), label77, FALSE, FALSE, 0);

  entry_where = gtk_entry_new ();
  gtk_widget_show (entry_where);
  gtk_box_pack_start (GTK_BOX (hbox34), entry_where, TRUE, TRUE, 0);

  label78 = gtk_label_new (_("   "));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox34), label78, FALSE, FALSE, 120);

  hbox41 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox41);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox41, TRUE, TRUE, 0);

  label100 = gtk_label_new (_("When:"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox41), label100, FALSE, FALSE, 0);

  entry_when = gtk_entry_new ();
  gtk_widget_show (entry_when);
  gtk_box_pack_start (GTK_BOX (hbox41), entry_when, TRUE, TRUE, 0);

  label101 = gtk_label_new (_("   "));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox41), label101, FALSE, FALSE, 120);

  label84 = gtk_label_new (_("   "));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (vbox11), label84, FALSE, FALSE, 0);

  dialog_action_area6 = GTK_DIALOG (RunDialog)->action_area;
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6), GTK_BUTTONBOX_END);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_container_add (GTK_CONTAINER (dialog_action_area6), hbuttonbox1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 8);

  run_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (run_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), run_ok);
  GTK_WIDGET_SET_FLAGS (run_ok, GTK_CAN_DEFAULT);

  run_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (run_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), run_cancel);
  GTK_WIDGET_SET_FLAGS (run_cancel, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) entry_job, "changed",
                    G_CALLBACK (on_entry_job_changed),
                    NULL);
  g_signal_connect ((gpointer) view_fileset_button, "clicked",
                    G_CALLBACK (on_view_fileset_clicked),
                    NULL);
  g_signal_connect ((gpointer) run_ok, "clicked",
                    G_CALLBACK (on_run_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) run_cancel, "clicked",
                    G_CALLBACK (on_run_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RunDialog, RunDialog, "RunDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (RunDialog, dialog_vbox7, "dialog_vbox7");
  GLADE_HOOKUP_OBJECT (RunDialog, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (RunDialog, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (RunDialog, label62, "label62");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (RunDialog, label63, "label63");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_job, "combo_job");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_job, "entry_job");
  GLADE_HOOKUP_OBJECT (RunDialog, label64, "label64");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_type, "combo_type");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_type, "entry_type");
  GLADE_HOOKUP_OBJECT (RunDialog, label65, "label65");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (RunDialog, label66, "label66");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_client, "combo_client");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_client, "entry_client");
  GLADE_HOOKUP_OBJECT (RunDialog, label67, "label67");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (RunDialog, label68, "label68");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_fileset, "combo_fileset");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_fileset, "entry_fileset");
  GLADE_HOOKUP_OBJECT (RunDialog, view_fileset_button, "view_fileset_button");
  GLADE_HOOKUP_OBJECT (RunDialog, label69, "label69");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (RunDialog, label70, "label70");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_level, "combo_level");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_level, "entry_level");
  GLADE_HOOKUP_OBJECT (RunDialog, label71, "label71");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (RunDialog, label72, "label72");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_pool, "combo_pool");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_pool, "entry_pool");
  GLADE_HOOKUP_OBJECT (RunDialog, label73, "label73");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox39, "hbox39");
  GLADE_HOOKUP_OBJECT (RunDialog, label96, "label96");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_storage, "combo_storage");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_storage, "entry_storage");
  GLADE_HOOKUP_OBJECT (RunDialog, label97, "label97");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox40, "hbox40");
  GLADE_HOOKUP_OBJECT (RunDialog, label98, "label98");
  GLADE_HOOKUP_OBJECT (RunDialog, combo_messages, "combo_messages");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_messages, "entry_messages");
  GLADE_HOOKUP_OBJECT (RunDialog, label99, "label99");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (RunDialog, label77, "label77");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_where, "entry_where");
  GLADE_HOOKUP_OBJECT (RunDialog, label78, "label78");
  GLADE_HOOKUP_OBJECT (RunDialog, hbox41, "hbox41");
  GLADE_HOOKUP_OBJECT (RunDialog, label100, "label100");
  GLADE_HOOKUP_OBJECT (RunDialog, entry_when, "entry_when");
  GLADE_HOOKUP_OBJECT (RunDialog, label101, "label101");
  GLADE_HOOKUP_OBJECT (RunDialog, label84, "label84");
  GLADE_HOOKUP_OBJECT_NO_REF (RunDialog, dialog_action_area6, "dialog_action_area6");
  GLADE_HOOKUP_OBJECT (RunDialog, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (RunDialog, run_ok, "run_ok");
  GLADE_HOOKUP_OBJECT (RunDialog, run_cancel, "run_cancel");

  return RunDialog;
}

GtkWidget*
create_restore_files (void)
{
  GtkWidget *restore_files;
  GtkWidget *vbox13;
  GtkWidget *scrolledwindow4;
  GtkWidget *ctree2;
  GtkWidget *hbox38;
  GtkWidget *label88;
  GtkWidget *entry25;
  GtkWidget *hbox44;
  GtkWidget *label105;
  GtkWidget *restore_file;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  restore_files = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (restore_files), _("Restore File Selection"));
  gtk_window_set_modal (GTK_WINDOW (restore_files), TRUE);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_container_add (GTK_CONTAINER (restore_files), vbox13);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox13), scrolledwindow4, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow4, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  ctree2 = gtk_tree_view_new ();
  gtk_widget_show (ctree2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), ctree2);

  hbox38 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox38);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox38, FALSE, TRUE, 0);

  label88 = gtk_label_new (_(" cwd:"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox38), label88, FALSE, TRUE, 0);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_box_pack_start (GTK_BOX (hbox38), entry25, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (entry25, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, entry25, _("Enter Commands Here"), NULL);

  hbox44 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox44);
  gtk_box_pack_start (GTK_BOX (vbox13), hbox44, FALSE, TRUE, 0);

  label105 = gtk_label_new (_(" "));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox44), label105, TRUE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label105), GTK_JUSTIFY_FILL);
  gtk_misc_set_padding (GTK_MISC (label105), 59, 0);

  restore_file = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (restore_file);
  gtk_box_pack_start (GTK_BOX (hbox44), restore_file, TRUE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (restore_file), 9);

  g_signal_connect ((gpointer) entry25, "key_press_event",
                    G_CALLBACK (on_entry1_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) entry25, "key_release_event",
                    G_CALLBACK (on_entry1_key_release_event),
                    NULL);
  g_signal_connect ((gpointer) restore_file, "clicked",
                    G_CALLBACK (on_restore_file_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (restore_files, restore_files, "restore_files");
  GLADE_HOOKUP_OBJECT (restore_files, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (restore_files, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (restore_files, ctree2, "ctree2");
  GLADE_HOOKUP_OBJECT (restore_files, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (restore_files, label88, "label88");
  GLADE_HOOKUP_OBJECT (restore_files, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (restore_files, hbox44, "hbox44");
  GLADE_HOOKUP_OBJECT (restore_files, label105, "label105");
  GLADE_HOOKUP_OBJECT (restore_files, restore_file, "restore_file");
  GLADE_HOOKUP_OBJECT_NO_REF (restore_files, tooltips, "tooltips");

  gtk_widget_grab_focus (entry25);
  gtk_widget_grab_default (entry25);
  return restore_files;
}

GtkWidget*
create_restore_dialog (void)
{
  GtkWidget *restore_dialog;
  GtkWidget *dialog_vbox8;
  GtkWidget *hbox42;
  GtkWidget *frame3;
  GtkWidget *hbox43;
  GtkWidget *label102;
  GtkWidget *vbox15;
  GtkWidget *label103;
  GtkWidget *rb_most_recent;
  GSList *rb_most_recent_group = NULL;
  GtkWidget *rb_jobs;
  GSList *rb_jobs_group = NULL;
  GtkWidget *rb_file;
  GSList *rb_file_group = NULL;
  GtkWidget *label104;
  GtkWidget *label106;
  GtkWidget *vbox14;
  GtkWidget *apply_button;
  GtkWidget *dialog_action_area7;
  GtkWidget *hbuttonbox2;
  GtkWidget *restore_ok;
  GtkWidget *restore_cancel;

  restore_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (restore_dialog), _("Restore Files"));
  gtk_window_set_modal (GTK_WINDOW (restore_dialog), TRUE);

  dialog_vbox8 = GTK_DIALOG (restore_dialog)->vbox;
  gtk_widget_show (dialog_vbox8);

  hbox42 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox42);
  gtk_box_pack_start (GTK_BOX (dialog_vbox8), hbox42, TRUE, TRUE, 0);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (hbox42), frame3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 8);

  hbox43 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox43);
  gtk_container_add (GTK_CONTAINER (frame3), hbox43);

  label102 = gtk_label_new (_("         "));
  gtk_widget_show (label102);
  gtk_box_pack_end (GTK_BOX (hbox43), label102, FALSE, FALSE, 0);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox15);
  gtk_box_pack_start (GTK_BOX (hbox43), vbox15, TRUE, TRUE, 0);

  label103 = gtk_label_new ("");
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (vbox15), label103, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label103), 0, 2);

  rb_most_recent = gtk_radio_button_new_with_mnemonic (NULL, _("Select most recent backup"));
  gtk_widget_show (rb_most_recent);
  gtk_box_pack_start (GTK_BOX (vbox15), rb_most_recent, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (rb_most_recent), 3);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_most_recent), rb_most_recent_group);
  rb_most_recent_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_most_recent));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (rb_most_recent), TRUE);

  rb_jobs = gtk_radio_button_new_with_mnemonic (NULL, _("Select list of Jobs"));
  gtk_widget_show (rb_jobs);
  gtk_box_pack_start (GTK_BOX (vbox15), rb_jobs, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (rb_jobs), 5);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_jobs), rb_jobs_group);
  rb_jobs_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_jobs));

  rb_file = gtk_radio_button_new_with_mnemonic (NULL, _("Find a specific file"));
  gtk_widget_show (rb_file);
  gtk_box_pack_start (GTK_BOX (vbox15), rb_file, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (rb_file), 4);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_file), rb_file_group);
  rb_file_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_file));

  label104 = gtk_label_new ("");
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (vbox15), label104, FALSE, FALSE, 0);

  label106 = gtk_label_new (_("Select by:"));
  gtk_widget_show (label106);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label106);
  gtk_label_set_justify (GTK_LABEL (label106), GTK_JUSTIFY_LEFT);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (hbox42), vbox14, FALSE, FALSE, 0);

  apply_button = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (apply_button);
  gtk_box_pack_start (GTK_BOX (vbox14), apply_button, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (apply_button), 50);

  dialog_action_area7 = GTK_DIALOG (restore_dialog)->action_area;
  gtk_widget_show (dialog_action_area7);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area7), GTK_BUTTONBOX_END);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_container_add (GTK_CONTAINER (dialog_action_area7), hbuttonbox2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox2), 8);

  restore_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (restore_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), restore_ok);
  GTK_WIDGET_SET_FLAGS (restore_ok, GTK_CAN_DEFAULT);

  restore_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (restore_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), restore_cancel);
  GTK_WIDGET_SET_FLAGS (restore_cancel, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) apply_button, "clicked",
                    G_CALLBACK (on_apply_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) restore_ok, "clicked",
                    G_CALLBACK (on_restore_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) restore_cancel, "clicked",
                    G_CALLBACK (on_restore_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (restore_dialog, restore_dialog, "restore_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (restore_dialog, dialog_vbox8, "dialog_vbox8");
  GLADE_HOOKUP_OBJECT (restore_dialog, hbox42, "hbox42");
  GLADE_HOOKUP_OBJECT (restore_dialog, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (restore_dialog, hbox43, "hbox43");
  GLADE_HOOKUP_OBJECT (restore_dialog, label102, "label102");
  GLADE_HOOKUP_OBJECT (restore_dialog, vbox15, "vbox15");
  GLADE_HOOKUP_OBJECT (restore_dialog, label103, "label103");
  GLADE_HOOKUP_OBJECT (restore_dialog, rb_most_recent, "rb_most_recent");
  GLADE_HOOKUP_OBJECT (restore_dialog, rb_jobs, "rb_jobs");
  GLADE_HOOKUP_OBJECT (restore_dialog, rb_file, "rb_file");
  GLADE_HOOKUP_OBJECT (restore_dialog, label104, "label104");
  GLADE_HOOKUP_OBJECT (restore_dialog, label106, "label106");
  GLADE_HOOKUP_OBJECT (restore_dialog, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (restore_dialog, apply_button, "apply_button");
  GLADE_HOOKUP_OBJECT_NO_REF (restore_dialog, dialog_action_area7, "dialog_action_area7");
  GLADE_HOOKUP_OBJECT (restore_dialog, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (restore_dialog, restore_ok, "restore_ok");
  GLADE_HOOKUP_OBJECT (restore_dialog, restore_cancel, "restore_cancel");

  return restore_dialog;
}

GtkWidget*
create_label_dialog (void)
{
  GtkWidget *label_dialog;
  GtkWidget *dialog_vbox9;
  GtkWidget *vbox16;
  GtkWidget *label106;
  GtkWidget *hbox45;
  GtkWidget *label107;
  GtkWidget *label_combo_storage;
  GList *label_combo_storage_items = NULL;
  GtkWidget *entry26;
  GtkWidget *hbox46;
  GtkWidget *label109;
  GtkWidget *label_combo_pool;
  GList *label_combo_pool_items = NULL;
  GtkWidget *entry27;
  GtkWidget *hbox47;
  GtkWidget *label111;
  GtkWidget *label_entry_volume;
  GtkWidget *hbox48;
  GtkWidget *slot1;
  GtkObject *label_slot_adj;
  GtkWidget *label_slot;
  GtkWidget *label113;
  GtkWidget *dialog_action_area8;
  GtkWidget *hbuttonbox3;
  GtkWidget *label_ok;
  GtkWidget *label_cancel;

  label_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (label_dialog), _("Label a Volume"));
  gtk_window_set_modal (GTK_WINDOW (label_dialog), TRUE);

  dialog_vbox9 = GTK_DIALOG (label_dialog)->vbox;
  gtk_widget_show (dialog_vbox9);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox16);
  gtk_box_pack_start (GTK_BOX (dialog_vbox9), vbox16, FALSE, TRUE, 0);

  label106 = gtk_label_new (_("Label a Volume"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (vbox16), label106, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label106), 0, 9);

  hbox45 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox45);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox45, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox45), 5);

  label107 = gtk_label_new (_("Storage:"));
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (hbox45), label107, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label107), 0.15, 0.5);

  label_combo_storage = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (label_combo_storage)->popwin),
                     "GladeParentKey", label_combo_storage);
  gtk_widget_show (label_combo_storage);
  gtk_box_pack_start (GTK_BOX (hbox45), label_combo_storage, TRUE, TRUE, 15);
  gtk_combo_set_value_in_list (GTK_COMBO (label_combo_storage), TRUE, FALSE);
  label_combo_storage_items = g_list_append (label_combo_storage_items, (gpointer) "");
  label_combo_storage_items = g_list_append (label_combo_storage_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (label_combo_storage), label_combo_storage_items);
  g_list_free (label_combo_storage_items);

  entry26 = GTK_COMBO (label_combo_storage)->entry;
  gtk_widget_show (entry26);
  gtk_editable_set_editable (GTK_EDITABLE (entry26), FALSE);

  hbox46 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox46);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox46, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox46), 5);

  label109 = gtk_label_new (_("Pool:"));
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (hbox46), label109, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label109), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label109), 0.12, 0.5);

  label_combo_pool = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (label_combo_pool)->popwin),
                     "GladeParentKey", label_combo_pool);
  gtk_widget_show (label_combo_pool);
  gtk_box_pack_start (GTK_BOX (hbox46), label_combo_pool, TRUE, TRUE, 14);
  gtk_combo_set_value_in_list (GTK_COMBO (label_combo_pool), TRUE, FALSE);
  label_combo_pool_items = g_list_append (label_combo_pool_items, (gpointer) "");
  label_combo_pool_items = g_list_append (label_combo_pool_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (label_combo_pool), label_combo_pool_items);
  g_list_free (label_combo_pool_items);

  entry27 = GTK_COMBO (label_combo_pool)->entry;
  gtk_widget_show (entry27);
  gtk_editable_set_editable (GTK_EDITABLE (entry27), FALSE);

  hbox47 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox47);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox47, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox47), 5);

  label111 = gtk_label_new (_("Volume Name:"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox47), label111, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label111), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label111), 0.17, 0.5);

  label_entry_volume = gtk_entry_new ();
  gtk_widget_show (label_entry_volume);
  gtk_box_pack_start (GTK_BOX (hbox47), label_entry_volume, TRUE, TRUE, 0);

  hbox48 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox48);
  gtk_box_pack_start (GTK_BOX (vbox16), hbox48, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox48), 5);

  slot1 = gtk_label_new (_("Slot:"));
  gtk_widget_show (slot1);
  gtk_box_pack_start (GTK_BOX (hbox48), slot1, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (slot1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (slot1), 0.09, 0.5);

  label_slot_adj = gtk_adjustment_new (0, 0, 10000, 1, 10, 10);
  label_slot = gtk_spin_button_new (GTK_ADJUSTMENT (label_slot_adj), 1, 0);
  gtk_widget_show (label_slot);
  gtk_box_pack_start (GTK_BOX (hbox48), label_slot, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (label_slot), TRUE);

  label113 = gtk_label_new (_("   "));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (vbox16), label113, FALSE, FALSE, 0);

  dialog_action_area8 = GTK_DIALOG (label_dialog)->action_area;
  gtk_widget_show (dialog_action_area8);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area8), GTK_BUTTONBOX_END);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_container_add (GTK_CONTAINER (dialog_action_area8), hbuttonbox3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox3), 8);

  label_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (label_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), label_ok);
  GTK_WIDGET_SET_FLAGS (label_ok, GTK_CAN_DEFAULT);

  label_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (label_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), label_cancel);
  GTK_WIDGET_SET_FLAGS (label_cancel, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) label_ok, "clicked",
                    G_CALLBACK (on_label_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) label_cancel, "clicked",
                    G_CALLBACK (on_label_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (label_dialog, label_dialog, "label_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (label_dialog, dialog_vbox9, "dialog_vbox9");
  GLADE_HOOKUP_OBJECT (label_dialog, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (label_dialog, label106, "label106");
  GLADE_HOOKUP_OBJECT (label_dialog, hbox45, "hbox45");
  GLADE_HOOKUP_OBJECT (label_dialog, label107, "label107");
  GLADE_HOOKUP_OBJECT (label_dialog, label_combo_storage, "label_combo_storage");
  GLADE_HOOKUP_OBJECT (label_dialog, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (label_dialog, hbox46, "hbox46");
  GLADE_HOOKUP_OBJECT (label_dialog, label109, "label109");
  GLADE_HOOKUP_OBJECT (label_dialog, label_combo_pool, "label_combo_pool");
  GLADE_HOOKUP_OBJECT (label_dialog, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (label_dialog, hbox47, "hbox47");
  GLADE_HOOKUP_OBJECT (label_dialog, label111, "label111");
  GLADE_HOOKUP_OBJECT (label_dialog, label_entry_volume, "label_entry_volume");
  GLADE_HOOKUP_OBJECT (label_dialog, hbox48, "hbox48");
  GLADE_HOOKUP_OBJECT (label_dialog, slot1, "slot1");
  GLADE_HOOKUP_OBJECT (label_dialog, label_slot, "label_slot");
  GLADE_HOOKUP_OBJECT (label_dialog, label113, "label113");
  GLADE_HOOKUP_OBJECT_NO_REF (label_dialog, dialog_action_area8, "dialog_action_area8");
  GLADE_HOOKUP_OBJECT (label_dialog, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (label_dialog, label_ok, "label_ok");
  GLADE_HOOKUP_OBJECT (label_dialog, label_cancel, "label_cancel");

  return label_dialog;
}

