#!/bin/sh
rm -f 1
touch 1
for i in . console gnome-console cats dird filed filed/win32 \
     win32 win32/compat findlib lib wx-console stored tools \
     win32/wx-console win32/console win32/baculafd; do
  ls -1 $i/*.c $i/*.cpp $i/*.h $i/*.in 2>/dev/null >>1
done
cat 1 | $HOME/bin/lines
# rm -f 1
