#!/bin/sh
#
# Make full release
#
# Bacula git repos
bacula=${bacula:-/home/kern/bacula/k}
docs=${docs:-/home/kern/bacula/docs}
rescue=${rescue:-/home/kern/bacula/rescue}
export push=yes
export updatepo=yes

current=$(cd $bacula ; git branch | awk '/*/ { print $2 }')
branch=${1:-$current}

./makeclean
./makebacularel $bacula $branch
./makedocsrel $bacula $docs $branch
./makerescuerel $rescue $branch
./makewinrel $bacula $branch | tee win$$.log

grep -i warning win$$.log >/dev/null
if [ $? -eq 0 ] ; then
  echo " "
  echo "Warnings in win$$.log"
  exit 1
fi
grep -i error win$$.log >/dev/null
if [ $? -eq 0 ] ; then
  echo " "
  echo "Errors in win$$.log"
  exit 1
fi
rm -f win$$.log
