######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 18 09:40:56 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
RESOURCES = main.qrc

# Input
FORMS += main.ui
HEADERS += mainwindow.h
SOURCES += main.cpp
SOURCES += mainwindow.cpp
