######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 18 09:40:56 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += main.ui
SOURCES += main.cpp
