#!/bin/sh
/bin/cp -f scripts/bacula-dir-tape.conf bin/bacula-dir.conf
/bin/cp -f scripts/bacula-sd-tape.conf bin/bacula-sd.conf
/bin/cp -f scripts/test-bacula-fd.conf bin/bacula-fd.conf
/bin/cp -f scripts/test-console.conf bin/bconsole.conf

# get proper SD tape definitions
if [ x$USE_VTAPE = xyes ]; then
    cp -f scripts/vtape_tape_options bin/tape_options
else 
    cp -f scripts/linux_tape_options bin/tape_options
fi
if test x`uname` = xFreeBSD ; then
   cp -f scripts/freebsd_tape_options bin/tape_options
fi
