#!/bin/sh
/bin/cp -f scripts/new-test-bacula-dir.conf bin/bacula-dir.conf
/bin/cp -f scripts/test-bacula-sd.conf bin/bacula-sd.conf
/bin/cp -f scripts/crypto-bacula-fd.conf bin/bacula-fd.conf
/bin/cp -f scripts/test-console.conf bin/bconsole.conf
/bin/cp -f scripts/cryptokeypair.pem bin/cryptokeypair.pem
/bin/cp -f scripts/master2048.cert bin/master2048.cert
