#!/bin/sh
#
# Setup for using the Virtual Disk Changer (simulates tape changer)
#
/bin/cp -f scripts/bacula-dir-migration.conf bin/bacula-dir.conf
/bin/cp -f scripts/bacula-sd-migration.conf bin/bacula-sd.conf
/bin/cp -f scripts/test-bacula-fd.conf bin/bacula-fd.conf
/bin/cp -f scripts/test-console.conf bin/bconsole.conf
