#!/bin/sh
/bin/cp -f ${rscripts}/bacula-dir-tape.conf ${scripts}/bacula-dir.conf
/bin/cp -f ${rscripts}/bacula-sd-tape.conf ${scripts}/bacula-sd.conf
/bin/cp -f ${rscripts}/test-bacula-fd.conf ${scripts}/bacula-fd.conf
/bin/cp -f ${rscripts}/test-console.conf ${scripts}/bconsole.conf
/bin/cp -f ${rscripts}/test-console.conf ${scripts}/bat.conf

${rscripts}/set_tape_options
