#!/bin/sh

. scripts/functions

SCR=$cwd/bin/bacula-ctl
sed "s:BACDIRBIN=$cwd/bin:BACDIRBIN=$bin:" $SCR-dir > tmp/1
mv tmp/1 $SCR-dir
se   d -i "s:BACSDBIN=$cwd/bin:BACSDBIN=$bin:" $SCR-sd > tmp/1
mv tm  p/1 $SCR-sd
sed -i "s:BACFDBIN=$cwd/bin:BACFDBIN=$bin:" $SCR-fd > tmp/1
mv tmp/1 $SCR-fd
chmod -x $cwd/bin/bacula-{fd,sd,dir} $cwd/bin/bconsole    
chmod +x $SCR-*

