#!/bin/sh
#
#  Test if daemons start
#

TestName="pretest"
JobName=backup
error=0

. scripts/functions

copy_test_confs


cat <<END_OF_DATA >${cwd}/tmp/bconcmds
messages
quit
END_OF_DATA

start_test

run_bacula
if [ $? -ne 0 ]; then
   echo "Error: bconsole error"
   error=1
fi

bin/bacula-ctl-dir status >/dev/null
if [ $? -ne 0 ]; then
   echo "Error: bacula-dir failed to start"
   error=1
fi

bin/bacula-ctl-fd status >/dev/null
if [ $? -ne 0 ]; then
   echo "Error: bacula-fd failed to start"
   error=1
fi

bin/bacula-ctl-sd status >/dev/null
if [ $? -ne 0 ]; then
   echo "Error: bacula-sd failed to start"
   error=1
fi

stop_bacula

export dstat=0
export bstat=$error
export rstat=0

end_test

exit $error
