#!/bin/sh
#
# Script to setup running Bacula regression tests
#
cwd=`pwd`
if [ $# != 1 ] ; then
   echo "Arg 1 must be a Bacula release directory."
   echo " "
   exit 1
fi
if [ ! -d $1 ] ; then
   echo "Arg 1 must be a Bacula release directory."
   echo " "
   exit 1
fi
if [ ! -d ../depkgs ] ; then
   cd ..
   cwd=`pwd`
   echo "The regression scripts require ${cwd}/depkgs but not found!" 
   echo " "
   exit 1
fi
rm -rf build bin
cp -rp $1 build
cp scripts/regress-config build
cd build
./regress-config ${cwd}
make
make install
cp src/tools/testls ../bin

cd ..
bin/bacula stop
bin/create_sqlite_database
bin/drop_sqlite_tables
bin/make_sqlite_tables
bin/bacula start
bin/bacula stop
#
# Save Bacula default conf files for later use
#
cp -f bin/*.conf scripts
scripts/do_sed
