#!/bin/sh
#
# Script to setup running Bacula regression tests
#
cwd=`pwd`
if [ $# != 4 ] ; then
   echo "Incorrect number of arguments. Need:"
   echo "setup bacula-src depkgs email-address --with-DBNAME"
   echo " "
   exit 1
fi
if [ ! -d $1 ] ; then
   echo "Arg 1 must be a Bacula release directory."
   echo " "
   exit 1
fi
if [ ! -d $2 ] ; then
   cd ..
   cwd=`pwd`
   echo "The regression scripts require DEPKGS as arg 2 but not found!" 
   echo " "
   exit 1
fi
rm -rf build bin
# Copy new source
cp -rp $1 build
cp scripts/regress-config build
cd build
rm -f Makefile config.cache
# Run Bacula configuration, make, install
./regress-config ${cwd} $2 $3 $4
make
make install
cp src/tools/testls ../bin

cd ..
bin/bacula stop
cd bin
./create_bacula_database
./drop_bacula_tables
./make_bacula_tables
./grant_bacula_privileges
cd ..
# Start and stop Bacula to ensure conf files are OK
bin/bacula start
bin/bacula stop
#
# Save Bacula default conf files for later use
#
cp -f bin/*.conf scripts
