#!/bin/sh
#
#  Make the stupid bacula.def file so that we don't have to do it
#    manually
#
#  Kern Sibbald, June 2007
#  Rewritten by James Harper, October 2009
#


FILES="$@"
if [ "$FILES" = "" ]
then
  exit 1
fi

TOPDIR=`(cd ../../../..;pwd)`
TOPDIR=${DEPKGS:-${TOPDIR}}
VERSION=$1
shift
if [ "$VERSION" = 64 ]; then
   NM=${TOPDIR}/cross-tools/mingw-w64/bin/mingw32-nm
elif [ "$VERSION" = 32 ]; then
   NM=${TOPDIR}/cross-tools/mingw32/mingw32/bin/nm
else 
   echo "Usage: make_def [32|64] *.o" >&2
   exit 1
fi

echo LIBRARY bacula.dll
echo EXPORTS
echo ""

$NM \
 --defined-only --extern-only $@ | while read addr type sym
do
 sym=`echo $sym | cut -c2-`
 case "$type" in
  "B")
   echo $sym DATA
   ;;
  "T")
   echo $sym
   ;;
  "")
   echo "; $addr"
   ;;
 esac
done

