#!/bin/sh
#
# Shell script to update PostgreSQL tables from version 1.34 to 1.35.5
#
echo " "
echo "This script will update a Bacula PostgreSQL database from version 7 to 8"
echo "Depending on the size of your database,"
echo "this script may take several minutes to run."
echo " "
bindir=/home/kern/bacula/depkgs/sqlite

if $bindir/psql $* -f - <<END-OF-DATA
\c bacula

ALTER TABLE Media ADD COLUMN EndFile integer not null default 0;
ALTER TABLE Media ADD COLUMN EndBlock integer not null default 0;

UPDATE Filename SET Name='' WHERE Name=' ';

DELETE FROM Version;
INSERT INTO Version (VersionId) VALUES (8);

create table CDImages 
(
   MediaId integer not null,
   LastBurn timestamp without time zone not null,
   primary key (MediaId)
);

END-OF-DATA
then
   echo "Update of Bacula PostgreSQL tables succeeded."
else
   echo "Update of Bacula PostgreSQL tables failed."
fi
exit 0
