#!/bin/sh
#
# Shell script to update PostgreSQL tables from version 1.34 to 1.35.5
#
echo " "
echo "This script will update a Bacula PostgreSQL database from version 7 to 8"
echo "Depending on the size of your database,"
echo "this script may take several minutes to run."
echo " "
bindir=/home/kern/bacula/depkgs/sqlite

if $bindir/psql $* -f - <<END-OF-DATA
\c bacula

ALTER TABLE media ADD COLUMN EndFile integer;
UPDATE media SET EndFile=0;
ALTER TABLE media ALTER COLUMN EndFile SET NOT NULL;
ALTER TABLE media ADD COLUMN EndBlock integer;
UPDATE media SET EndBlock=0;
ALTER TABLE media ALTER COLUMN EndBlock SET NOT NULL;

UPDATE Filename SET Name='' WHERE Name=' ';

ALTER TABLE file ALTER COLUMN filenameid SET integer;

DELETE FROM Version;
INSERT INTO Version (VersionId) VALUES (8);

create index file_jobid_idx on file (jobid);
create index file_pathid_idx on file(pathid);
create index file_filenameid_idx on file(filenameid);
create index file_jpfid_idx on file (jobid, pathid, filenameid);

END-OF-DATA
then
   echo "Update of Bacula PostgreSQL tables succeeded."
else
   echo "Update of Bacula PostgreSQL tables failed."
fi
exit 0
