.\"                                      Hey, EMACS: -*- nroff -*-
.TH BACULA\-SMTP 1 "26 May 2006" "Kern Sibbald" "Network backup"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
 bsmtp \- Bacula's SMTP (mail delivery program)
.SH DESCRIPTION
.br
.SH AUTHOR
This manual page was written by Jose Luis Tallon
.nh 
<jltallon@adv\-solutions.net>.
